using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Security;
using System.Text;
using System.Xml.Linq;
using BankInsight.API.DTOs;

namespace BankInsight.API.Services;

public interface IReportExportService
{
    (byte[] Content, string ContentType, string FileName) Export(ReportExecutionResponseDTO report, string format, string generatedBy, string institutionName);
}

public class ReportExportService : IReportExportService
{
    private static readonly XNamespace SpreadsheetNs = "http://schemas.openxmlformats.org/spreadsheetml/2006/main";
    private static readonly XNamespace OfficeRelNs = "http://schemas.openxmlformats.org/officeDocument/2006/relationships";

    public (byte[] Content, string ContentType, string FileName) Export(ReportExecutionResponseDTO report, string format, string generatedBy, string institutionName)
    {
        var normalized = (format ?? "csv").Trim().ToLowerInvariant();
        var safeName = SanitizeFileName($"{report.ReportCode}_{DateTime.UtcNow:yyyyMMdd_HHmmss}");

        return normalized switch
        {
            "xlsx" => (BuildXlsx(report, generatedBy, institutionName), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", safeName + ".xlsx"),
            "pdf" => (BuildPdf(report, generatedBy, institutionName), "application/pdf", safeName + ".pdf"),
            _ => (BuildCsv(report, generatedBy, institutionName), "text/csv", safeName + ".csv")
        };
    }

    private static byte[] BuildCsv(ReportExecutionResponseDTO report, string generatedBy, string institutionName)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"Institution,{EscapeCsv(institutionName)}");
        sb.AppendLine($"Report,{EscapeCsv(report.ReportName)}");
        sb.AppendLine($"Generated At,{report.GeneratedAt:yyyy-MM-dd HH:mm:ss}");
        sb.AppendLine($"Generated By,{EscapeCsv(generatedBy)}");
        if (report.AppliedFilters.Count > 0)
        {
            sb.AppendLine($"Filters,{EscapeCsv(FilterSummary(report))}");
        }

        sb.AppendLine();
        sb.AppendLine(string.Join(",", report.Columns.Select(EscapeCsv)));
        foreach (var row in report.Rows)
        {
            sb.AppendLine(string.Join(",", report.Columns.Select(column => EscapeCsv(FormatValue(row.TryGetValue(column, out var value) ? value : null)))));
        }

        return Encoding.UTF8.GetBytes(sb.ToString());
    }

    private static byte[] BuildXlsx(ReportExecutionResponseDTO report, string generatedBy, string institutionName)
    {
        using var stream = new MemoryStream();
        using var archive = new ZipArchive(stream, ZipArchiveMode.Create, true);

        AddEntry(archive, "[Content_Types].xml", BuildContentTypesXml());
        AddEntry(archive, "_rels/.rels", BuildRootRelationshipsXml());
        AddEntry(archive, "docProps/app.xml", BuildAppPropertiesXml());
        AddEntry(archive, "docProps/core.xml", BuildCorePropertiesXml(report, generatedBy));
        AddEntry(archive, "xl/workbook.xml", BuildWorkbookXml());
        AddEntry(archive, "xl/_rels/workbook.xml.rels", BuildWorkbookRelationshipsXml());
        AddEntry(archive, "xl/styles.xml", BuildStylesXml());
        AddEntry(archive, "xl/worksheets/sheet1.xml", BuildSheetXml(report, generatedBy, institutionName));

        return stream.ToArray();
    }

    private static byte[] BuildPdf(ReportExecutionResponseDTO report, string generatedBy, string institutionName)
    {
        const decimal pageWidth = 842m;
        const decimal pageHeight = 595m;
        const decimal margin = 36m;
        const decimal rowHeight = 22m;
        const decimal tableTop = 238m;

        var logoText = GetLogoText(institutionName);
        var filterSummary = FilterSummary(report);
        var summaryMetrics = report.Summary.Take(4).ToList();
        var columnWidths = CalculatePdfColumnWidths(report.Columns, report.Rows, pageWidth - (margin * 2));
        var rowsPerPage = Math.Max(8, (int)Math.Floor((pageHeight - tableTop - 34m) / rowHeight));
        var totalPages = report.Rows.Count == 0 ? 1 : (int)Math.Ceiling(report.Rows.Count / (double)rowsPerPage);

        var objects = new List<string>
        {
            "1 0 obj << /Type /Catalog /Pages 2 0 R >> endobj",
            string.Empty,
            "3 0 obj << /Type /Font /Subtype /Type1 /BaseFont /Helvetica >> endobj",
            "4 0 obj << /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >> endobj"
        };
        var pageIds = new List<int>();

        for (var pageIndex = 0; pageIndex < totalPages; pageIndex++)
        {
            var pageRows = report.Rows.Skip(pageIndex * rowsPerPage).Take(rowsPerPage).ToList();
            var content = BuildPdfPageContent(
                report,
                generatedBy,
                institutionName,
                logoText,
                filterSummary,
                summaryMetrics,
                pageIndex + 1,
                totalPages,
                pageRows,
                columnWidths,
                pageWidth,
                pageHeight,
                margin,
                tableTop,
                rowHeight);

            var contentId = objects.Count + 1;
            objects.Add($"{contentId} 0 obj << /Length {Encoding.ASCII.GetByteCount(content)} >> stream\n{content}\nendstream endobj");

            var pageId = objects.Count + 1;
            pageIds.Add(pageId);
            objects.Add($"{pageId} 0 obj << /Type /Page /Parent 2 0 R /MediaBox [0 0 {pageWidth.ToString(CultureInfo.InvariantCulture)} {pageHeight.ToString(CultureInfo.InvariantCulture)}] /Resources << /Font << /F1 3 0 R /F2 4 0 R >> >> /Contents {contentId} 0 R >> endobj");
        }

        objects[1] = $"2 0 obj << /Type /Pages /Kids [{string.Join(" ", pageIds.Select(id => $"{id} 0 R"))}] /Count {pageIds.Count} >> endobj";

        var pdf = new StringBuilder();
        pdf.AppendLine("%PDF-1.4");
        var offsets = new List<int>();
        foreach (var obj in objects)
        {
            offsets.Add(Encoding.ASCII.GetByteCount(pdf.ToString()));
            pdf.AppendLine(obj);
        }

        var xrefOffset = Encoding.ASCII.GetByteCount(pdf.ToString());
        pdf.AppendLine("xref");
        pdf.AppendLine($"0 {objects.Count + 1}");
        pdf.AppendLine("0000000000 65535 f ");
        foreach (var offset in offsets)
        {
            pdf.AppendLine(offset.ToString("D10", CultureInfo.InvariantCulture) + " 00000 n ");
        }

        pdf.AppendLine($"trailer << /Size {objects.Count + 1} /Root 1 0 R >>");
        pdf.AppendLine("startxref");
        pdf.AppendLine(xrefOffset.ToString(CultureInfo.InvariantCulture));
        pdf.AppendLine("%%EOF");

        return Encoding.ASCII.GetBytes(pdf.ToString());
    }
    private static string BuildSheetXml(ReportExecutionResponseDTO report, string generatedBy, string institutionName)
    {
        var rows = new List<XElement>();
        var merges = new List<string> { "A2:F2", "A3:F3", "A4:F4", "A5:F5", "A6:F6", "A7:F7", "A9:F9" };
        var currentRow = 1;
        var logoText = GetLogoText(institutionName);

        rows.Add(Row(currentRow++, LogoCell(1, 1, logoText), TextCell(2, 1, "Presentation Export", 3)));
        rows.Add(Row(currentRow++, TextCell(1, 2, institutionName, 2)));
        rows.Add(Row(currentRow++, TextCell(1, 3, report.ReportName, 1)));
        rows.Add(Row(currentRow++, TextCell(1, 4, $"{report.Category} | {report.SubCategory}", 3)));
        rows.Add(Row(currentRow++, TextCell(1, 5, $"Generated on {report.GeneratedAt:dd MMM yyyy HH:mm} UTC", 3)));
        rows.Add(Row(currentRow++, TextCell(1, 6, $"Prepared by {generatedBy}", 3)));
        rows.Add(Row(currentRow++, TextCell(1, 7, $"Applied filters: {FilterSummary(report)}", 8)));
        rows.Add(Row(currentRow++));
        rows.Add(Row(currentRow++, TextCell(1, 9, "Report Data", 5)));
        rows.Add(Row(currentRow++, report.Columns.Select((column, index) => TextCell(index + 1, currentRow - 1, HumanizeColumnName(column), 4)).ToArray()));

        foreach (var row in report.Rows)
        {
            rows.Add(Row(currentRow, report.Columns.Select((column, index) => BuildDataCell(index + 1, currentRow, row.TryGetValue(column, out var value) ? value : null)).ToArray()));
            currentRow++;
        }

        if (report.Rows.Count > 0)
        {
            var totals = BuildTotalsRow(report);
            if (totals.Any(x => !string.IsNullOrWhiteSpace(x.Value)))
            {
                rows.Add(Row(currentRow++, totals.Select((cell, index) => BuildStyledValueCell(index + 1, currentRow - 1, cell.Value, cell.Style)).ToArray()));
            }
        }

        if (report.Summary.Count > 0)
        {
            rows.Add(Row(currentRow++));
            rows.Add(Row(currentRow++, TextCell(1, currentRow - 1, "Executive Summary", 5)));
            foreach (var metric in report.Summary.Take(8))
            {
                rows.Add(Row(currentRow, TextCell(1, currentRow, metric.Label, 3), TextCell(2, currentRow, metric.Value, 9), TextCell(3, currentRow, metric.Helper ?? string.Empty, 8)));
                currentRow++;
            }
        }

        if (report.ValidationMessages.Count > 0)
        {
            rows.Add(Row(currentRow++));
            rows.Add(Row(currentRow++, TextCell(1, currentRow - 1, "Validation Notes", 5)));
            foreach (var message in report.ValidationMessages.Take(6))
            {
                rows.Add(Row(currentRow++, TextCell(1, currentRow - 1, message, 8)));
            }
        }

        var worksheet = new XDocument(
            new XDeclaration("1.0", "UTF-8", "yes"),
            new XElement(
                SpreadsheetNs + "worksheet",
                new XAttribute(XNamespace.Xmlns + "r", OfficeRelNs.NamespaceName),
                BuildColumnsXml(CalculateExcelColumnWidths(report)),
                new XElement(
                    SpreadsheetNs + "sheetViews",
                    new XElement(
                        SpreadsheetNs + "sheetView",
                        new XAttribute("workbookViewId", 0),
                        new XElement(SpreadsheetNs + "pane", new XAttribute("ySplit", 10), new XAttribute("topLeftCell", "A11"), new XAttribute("state", "frozen"), new XAttribute("activePane", "bottomLeft")))),
                new XElement(SpreadsheetNs + "sheetFormatPr", new XAttribute("defaultRowHeight", 18)),
                new XElement(SpreadsheetNs + "sheetData", rows),
                new XElement(SpreadsheetNs + "mergeCells", new XAttribute("count", merges.Count), merges.Select(item => new XElement(SpreadsheetNs + "mergeCell", new XAttribute("ref", item)))),
                report.Columns.Count > 0 ? new XElement(SpreadsheetNs + "autoFilter", new XAttribute("ref", $"A10:{CellReference(report.Columns.Count, Math.Max(10, 9 + report.Rows.Count))}")) : null,
                new XElement(SpreadsheetNs + "pageSetup", new XAttribute("orientation", report.Columns.Count > 6 ? "landscape" : "portrait"), new XAttribute("paperSize", 9)),
                new XElement(SpreadsheetNs + "pageMargins", new XAttribute("left", 0.35), new XAttribute("right", 0.35), new XAttribute("top", 0.55), new XAttribute("bottom", 0.55), new XAttribute("header", 0.2), new XAttribute("footer", 0.2))));

        return worksheet.ToString(SaveOptions.DisableFormatting);
    }

    private static XElement BuildColumnsXml(IEnumerable<double> widths) =>
        new(SpreadsheetNs + "cols",
            widths.Select((width, index) => new XElement(
                SpreadsheetNs + "col",
                new XAttribute("min", index + 1),
                new XAttribute("max", index + 1),
                new XAttribute("width", width.ToString("0.##", CultureInfo.InvariantCulture)),
                new XAttribute("customWidth", 1))));

    private static IEnumerable<double> CalculateExcelColumnWidths(ReportExecutionResponseDTO report)
    {
        var widths = new List<double>();
        foreach (var column in report.Columns)
        {
            var longest = Math.Max(HumanizeColumnName(column).Length, report.Rows.Select(row => row.TryGetValue(column, out var value) ? FormatValue(value).Length : 0).DefaultIfEmpty(0).Max());
            widths.Add(Math.Clamp(longest + 4, 12, 28));
        }

        while (widths.Count < 6)
        {
            widths.Add(18);
        }

        return widths;
    }

    private static List<(string Value, int Style)> BuildTotalsRow(ReportExecutionResponseDTO report)
    {
        var result = new List<(string Value, int Style)>();
        var labelPlaced = false;
        foreach (var column in report.Columns)
        {
            var values = report.Rows.Select(row => row.TryGetValue(column, out var value) ? value : null).ToList();
            var numericValues = values.Where(IsNumeric).Select(value => Convert.ToDecimal(value, CultureInfo.InvariantCulture)).ToList();
            if (numericValues.Count == values.Count && numericValues.Count > 0)
            {
                if (!labelPlaced)
                {
                    result.Add(("Total", 5));
                    labelPlaced = true;
                }
                else
                {
                    result.Add((decimal.Round(numericValues.Sum(), 2, MidpointRounding.AwayFromZero).ToString("0.00", CultureInfo.InvariantCulture), 9));
                }
            }
            else
            {
                result.Add((labelPlaced ? string.Empty : "Total", labelPlaced ? 8 : 5));
                labelPlaced = true;
            }
        }

        return result;
    }

    private static XElement BuildDataCell(int columnIndex, int rowIndex, object? value)
    {
        if (TryGetDateSerial(value, out var serial))
        {
            return NumberCell(columnIndex, rowIndex, serial, 7);
        }

        if (IsNumeric(value))
        {
            return NumberCell(columnIndex, rowIndex, Convert.ToDecimal(value, CultureInfo.InvariantCulture), 6);
        }

        return TextCell(columnIndex, rowIndex, FormatValue(value), 8);
    }

    private static XElement BuildStyledValueCell(int columnIndex, int rowIndex, string value, int style)
    {
        if (decimal.TryParse(value, NumberStyles.Any, CultureInfo.InvariantCulture, out var numeric))
        {
            return NumberCell(columnIndex, rowIndex, numeric, style);
        }

        return TextCell(columnIndex, rowIndex, value, style);
    }

    private static string BuildContentTypesXml() =>
        "<?xml version=\"1.0\" encoding=\"UTF-8\"?>" +
        "<Types xmlns=\"http://schemas.openxmlformats.org/package/2006/content-types\">" +
        "<Default Extension=\"rels\" ContentType=\"application/vnd.openxmlformats-package.relationships+xml\"/>" +
        "<Default Extension=\"xml\" ContentType=\"application/xml\"/>" +
        "<Override PartName=\"/xl/workbook.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml\"/>" +
        "<Override PartName=\"/xl/worksheets/sheet1.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml\"/>" +
        "<Override PartName=\"/xl/styles.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml\"/>" +
        "<Override PartName=\"/docProps/core.xml\" ContentType=\"application/vnd.openxmlformats-package.core-properties+xml\"/>" +
        "<Override PartName=\"/docProps/app.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.extended-properties+xml\"/>" +
        "</Types>";

    private static string BuildRootRelationshipsXml() =>
        "<?xml version=\"1.0\" encoding=\"UTF-8\"?>" +
        "<Relationships xmlns=\"http://schemas.openxmlformats.org/package/2006/relationships\">" +
        "<Relationship Id=\"rId1\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument\" Target=\"xl/workbook.xml\"/>" +
        "<Relationship Id=\"rId2\" Type=\"http://schemas.openxmlformats.org/package/2006/relationships/metadata/core-properties\" Target=\"docProps/core.xml\"/>" +
        "<Relationship Id=\"rId3\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/extended-properties\" Target=\"docProps/app.xml\"/>" +
        "</Relationships>";

    private static string BuildWorkbookXml() =>
        "<?xml version=\"1.0\" encoding=\"UTF-8\"?>" +
        "<workbook xmlns=\"http://schemas.openxmlformats.org/spreadsheetml/2006/main\" xmlns:r=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships\">" +
        "<sheets><sheet name=\"Report\" sheetId=\"1\" r:id=\"rId1\"/></sheets></workbook>";

    private static string BuildWorkbookRelationshipsXml() =>
        "<?xml version=\"1.0\" encoding=\"UTF-8\"?>" +
        "<Relationships xmlns=\"http://schemas.openxmlformats.org/package/2006/relationships\">" +
        "<Relationship Id=\"rId1\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet\" Target=\"worksheets/sheet1.xml\"/>" +
        "<Relationship Id=\"rId2\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles\" Target=\"styles.xml\"/>" +
        "</Relationships>";

    private static string BuildStylesXml() =>
        "<?xml version=\"1.0\" encoding=\"UTF-8\"?>" +
        "<styleSheet xmlns=\"http://schemas.openxmlformats.org/spreadsheetml/2006/main\">" +
        "<numFmts count=\"2\"><numFmt numFmtId=\"164\" formatCode=\"dd\\ mmm\\ yyyy\\ hh:mm\"/><numFmt numFmtId=\"165\" formatCode=\"# ##0.00\"/></numFmts>" +
        "<fonts count=\"6\">" +
        "<font><sz val=\"11\"/><color rgb=\"FF1F2937\"/><name val=\"Aptos\"/><family val=\"2\"/></font>" +
        "<font><b/><sz val=\"18\"/><color rgb=\"FF0F172A\"/><name val=\"Aptos Display\"/><family val=\"2\"/></font>" +
        "<font><b/><sz val=\"13\"/><color rgb=\"FF1F2937\"/><name val=\"Aptos\"/><family val=\"2\"/></font>" +
        "<font><sz val=\"10\"/><color rgb=\"FF475569\"/><name val=\"Aptos\"/><family val=\"2\"/></font>" +
        "<font><b/><sz val=\"10\"/><color rgb=\"FFFFFFFF\"/><name val=\"Aptos\"/><family val=\"2\"/></font>" +
        "<font><b/><sz val=\"11\"/><color rgb=\"FFFFFFFF\"/><name val=\"Aptos\"/><family val=\"2\"/></font>" +
        "</fonts>" +
        "<fills count=\"7\">" +
        "<fill><patternFill patternType=\"none\"/></fill>" +
        "<fill><patternFill patternType=\"gray125\"/></fill>" +
        "<fill><patternFill patternType=\"solid\"><fgColor rgb=\"FF0F172A\"/><bgColor indexed=\"64\"/></patternFill></fill>" +
        "<fill><patternFill patternType=\"solid\"><fgColor rgb=\"FFF8FAFC\"/><bgColor indexed=\"64\"/></patternFill></fill>" +
        "<fill><patternFill patternType=\"solid\"><fgColor rgb=\"FFE2E8F0\"/><bgColor indexed=\"64\"/></patternFill></fill>" +
        "<fill><patternFill patternType=\"solid\"><fgColor rgb=\"FF1D4ED8\"/><bgColor indexed=\"64\"/></patternFill></fill>" +
        "<fill><patternFill patternType=\"solid\"><fgColor rgb=\"FFDBEAFE\"/><bgColor indexed=\"64\"/></patternFill></fill>" +
        "</fills>" +
        "<borders count=\"2\">" +
        "<border><left/><right/><top/><bottom/><diagonal/></border>" +
        "<border><left style=\"thin\"><color rgb=\"FFD1D5DB\"/></left><right style=\"thin\"><color rgb=\"FFD1D5DB\"/></right><top style=\"thin\"><color rgb=\"FFD1D5DB\"/></top><bottom style=\"thin\"><color rgb=\"FFD1D5DB\"/></bottom><diagonal/></border>" +
        "</borders>" +
        "<cellStyleXfs count=\"1\"><xf numFmtId=\"0\" fontId=\"0\" fillId=\"0\" borderId=\"0\"/></cellStyleXfs>" +
        "<cellXfs count=\"10\">" +
        "<xf numFmtId=\"0\" fontId=\"0\" fillId=\"0\" borderId=\"0\" xfId=\"0\"/>" +
        "<xf numFmtId=\"0\" fontId=\"1\" fillId=\"0\" borderId=\"0\" xfId=\"0\" applyFont=\"1\"/>" +
        "<xf numFmtId=\"0\" fontId=\"2\" fillId=\"0\" borderId=\"0\" xfId=\"0\" applyFont=\"1\"/>" +
        "<xf numFmtId=\"0\" fontId=\"3\" fillId=\"0\" borderId=\"0\" xfId=\"0\" applyFont=\"1\"/>" +
        "<xf numFmtId=\"0\" fontId=\"4\" fillId=\"2\" borderId=\"1\" xfId=\"0\" applyFont=\"1\" applyFill=\"1\" applyBorder=\"1\" applyAlignment=\"1\"><alignment horizontal=\"center\" vertical=\"center\"/></xf>" +
        "<xf numFmtId=\"0\" fontId=\"5\" fillId=\"5\" borderId=\"1\" xfId=\"0\" applyFont=\"1\" applyFill=\"1\" applyBorder=\"1\" applyAlignment=\"1\"><alignment horizontal=\"left\" vertical=\"center\"/></xf>" +
        "<xf numFmtId=\"165\" fontId=\"0\" fillId=\"3\" borderId=\"1\" xfId=\"0\" applyNumberFormat=\"1\" applyFill=\"1\" applyBorder=\"1\" applyAlignment=\"1\"><alignment horizontal=\"right\" vertical=\"center\"/></xf>" +
        "<xf numFmtId=\"164\" fontId=\"0\" fillId=\"3\" borderId=\"1\" xfId=\"0\" applyNumberFormat=\"1\" applyFill=\"1\" applyBorder=\"1\" applyAlignment=\"1\"><alignment horizontal=\"left\" vertical=\"center\"/></xf>" +
        "<xf numFmtId=\"0\" fontId=\"0\" fillId=\"3\" borderId=\"1\" xfId=\"0\" applyFill=\"1\" applyBorder=\"1\" applyAlignment=\"1\"><alignment wrapText=\"1\" vertical=\"top\"/></xf>" +
        "<xf numFmtId=\"165\" fontId=\"2\" fillId=\"6\" borderId=\"1\" xfId=\"0\" applyNumberFormat=\"1\" applyFont=\"1\" applyFill=\"1\" applyBorder=\"1\" applyAlignment=\"1\"><alignment horizontal=\"right\" vertical=\"center\"/></xf>" +
        "</cellXfs>" +
        "</styleSheet>";

    private static string BuildCorePropertiesXml(ReportExecutionResponseDTO report, string generatedBy)
    {
        var created = DateTime.UtcNow.ToString("yyyy-MM-ddTHH:mm:ssZ", CultureInfo.InvariantCulture);
        return $"<?xml version=\"1.0\" encoding=\"UTF-8\"?><cp:coreProperties xmlns:cp=\"http://schemas.openxmlformats.org/package/2006/metadata/core-properties\" xmlns:dc=\"http://purl.org/dc/elements/1.1/\" xmlns:dcterms=\"http://purl.org/dc/terms/\" xmlns:dcmitype=\"http://purl.org/dc/dcmitype/\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"><dc:title>{SecurityElement.Escape(report.ReportName)}</dc:title><dc:creator>{SecurityElement.Escape(generatedBy)}</dc:creator><cp:lastModifiedBy>{SecurityElement.Escape(generatedBy)}</cp:lastModifiedBy><dcterms:created xsi:type=\"dcterms:W3CDTF\">{created}</dcterms:created><dcterms:modified xsi:type=\"dcterms:W3CDTF\">{created}</dcterms:modified></cp:coreProperties>";
    }

    private static string BuildAppPropertiesXml() =>
        "<?xml version=\"1.0\" encoding=\"UTF-8\"?><Properties xmlns=\"http://schemas.openxmlformats.org/officeDocument/2006/extended-properties\" xmlns:vt=\"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes\"><Application>BankInsight</Application></Properties>";
    private static string BuildPdfPageContent(
        ReportExecutionResponseDTO report,
        string generatedBy,
        string institutionName,
        string logoText,
        string filterSummary,
        List<ReportSummaryMetricDTO> summaryMetrics,
        int pageNumber,
        int totalPages,
        List<Dictionary<string, object?>> rows,
        List<decimal> columnWidths,
        decimal pageWidth,
        decimal pageHeight,
        decimal margin,
        decimal tableTop,
        decimal rowHeight)
    {
        var sb = new StringBuilder();
        DrawFilledRect(sb, margin, pageHeight - 96m, pageWidth - (margin * 2), 56m, "0.09 0.18 0.34");
        DrawFilledRect(sb, margin + 12m, pageHeight - 82m, 46m, 28m, "0.11 0.30 0.85");
        DrawText(sb, "F2", 12m, margin + 20m, pageHeight - 64m, logoText, "1 1 1");
        DrawText(sb, "F2", 20m, margin + 72m, pageHeight - 58m, institutionName, "1 1 1");
        DrawText(sb, "F1", 10m, margin + 72m, pageHeight - 76m, "Enterprise reporting export", "0.88 0.92 0.98");

        DrawText(sb, "F2", 18m, margin, pageHeight - 122m, report.ReportName, "0.05 0.09 0.16");
        DrawText(sb, "F1", 10m, margin, pageHeight - 140m, $"{report.Category} | {report.SubCategory}", "0.36 0.43 0.51");
        DrawText(sb, "F1", 10m, pageWidth - 220m, pageHeight - 122m, $"Generated {report.GeneratedAt:dd MMM yyyy HH:mm} UTC", "0.36 0.43 0.51");
        DrawText(sb, "F1", 10m, pageWidth - 220m, pageHeight - 140m, $"Prepared by {generatedBy}", "0.36 0.43 0.51");

        var metricCount = Math.Max(1, summaryMetrics.Count);
        var metricBoxWidth = (pageWidth - (margin * 2) - ((metricCount - 1) * 8m)) / metricCount;
        var metricY = pageHeight - 185m;
        for (var index = 0; index < metricCount; index++)
        {
            var metric = summaryMetrics.Count > index ? summaryMetrics[index] : new ReportSummaryMetricDTO { Label = "Rows", Value = report.Rows.Count.ToString("N0", CultureInfo.InvariantCulture) };
            var x = margin + (index * (metricBoxWidth + 8m));
            DrawFilledRect(sb, x, metricY, metricBoxWidth, 36m, "0.96 0.98 1");
            DrawText(sb, "F1", 8.5m, x + 8m, metricY + 24m, metric.Label, "0.29 0.33 0.38");
            DrawText(sb, "F2", 12m, x + 8m, metricY + 10m, Truncate(metric.Value, 22), "0.05 0.09 0.16");
        }

        DrawText(sb, "F1", 9m, margin, pageHeight - 210m, $"Filters: {Truncate(filterSummary, 115)}", "0.29 0.33 0.38");

        var tableY = pageHeight - tableTop;
        DrawFilledRect(sb, margin, tableY, pageWidth - (margin * 2), rowHeight, "0.11 0.30 0.85");

        var xCursor = margin;
        for (var columnIndex = 0; columnIndex < report.Columns.Count; columnIndex++)
        {
            DrawText(sb, "F2", 9m, xCursor + 4m, tableY + 7m, Truncate(HumanizeColumnName(report.Columns[columnIndex]), MaxCharsForWidth(columnWidths[columnIndex])), "1 1 1");
            DrawStrokeRect(sb, xCursor, tableY, columnWidths[columnIndex], rowHeight, "0.74 0.84 0.98");
            xCursor += columnWidths[columnIndex];
        }

        var yCursor = tableY - rowHeight;
        for (var rowIndex = 0; rowIndex < rows.Count; rowIndex++)
        {
            if (rowIndex % 2 == 0)
            {
                DrawFilledRect(sb, margin, yCursor, pageWidth - (margin * 2), rowHeight, "0.98 0.99 1");
            }

            xCursor = margin;
            for (var columnIndex = 0; columnIndex < report.Columns.Count; columnIndex++)
            {
                var column = report.Columns[columnIndex];
                var value = rows[rowIndex].TryGetValue(column, out var raw) ? raw : null;
                var text = Truncate(FormatValue(value), MaxCharsForWidth(columnWidths[columnIndex]));
                var textX = IsNumeric(value) ? xCursor + columnWidths[columnIndex] - 4m - (text.Length * 4.1m) : xCursor + 4m;
                DrawText(sb, "F1", 8.5m, textX, yCursor + 7m, text, "0.11 0.17 0.24");
                DrawStrokeRect(sb, xCursor, yCursor, columnWidths[columnIndex], rowHeight, "0.85 0.89 0.94");
                xCursor += columnWidths[columnIndex];
            }

            yCursor -= rowHeight;
        }

        DrawText(sb, "F1", 9m, margin, 18m, "Confidential banking information. Prepared for presentation use.", "0.45 0.49 0.56");
        DrawText(sb, "F1", 9m, pageWidth - 92m, 18m, $"Page {pageNumber}/{totalPages}", "0.45 0.49 0.56");
        return sb.ToString();
    }

    private static List<decimal> CalculatePdfColumnWidths(List<string> columns, List<Dictionary<string, object?>> rows, decimal availableWidth)
    {
        var weights = columns.Select(column =>
        {
            var headerLength = HumanizeColumnName(column).Length;
            var valueLength = rows.Select(row => row.TryGetValue(column, out var value) ? FormatValue(value).Length : 0).DefaultIfEmpty(0).Max();
            return Math.Max(10, Math.Min(30, Math.Max(headerLength, valueLength)));
        }).ToList();

        var totalWeight = weights.Sum();
        var widths = weights.Select(weight => decimal.Round(availableWidth * (weight / totalWeight), 2, MidpointRounding.AwayFromZero)).ToList();
        for (var index = 0; index < widths.Count; index++)
        {
            widths[index] = Math.Clamp(widths[index], 70m, 180m);
        }

        var adjustedTotal = widths.Sum();
        if (widths.Count > 0)
        {
            widths[^1] += availableWidth - adjustedTotal;
        }

        return widths;
    }

    private static int MaxCharsForWidth(decimal width) => Math.Max(8, (int)Math.Floor((double)(width / 5.4m)));

    private static void DrawFilledRect(StringBuilder sb, decimal x, decimal y, decimal width, decimal height, string rgb)
    {
        sb.AppendLine($"{rgb} rg");
        sb.AppendLine($"{Fmt(x)} {Fmt(y)} {Fmt(width)} {Fmt(height)} re f");
    }

    private static void DrawStrokeRect(StringBuilder sb, decimal x, decimal y, decimal width, decimal height, string rgb)
    {
        sb.AppendLine($"{rgb} RG");
        sb.AppendLine("0.5 w");
        sb.AppendLine($"{Fmt(x)} {Fmt(y)} {Fmt(width)} {Fmt(height)} re S");
    }

    private static void DrawText(StringBuilder sb, string font, decimal size, decimal x, decimal y, string text, string rgb)
    {
        sb.AppendLine("BT");
        sb.AppendLine($"{rgb} rg");
        sb.AppendLine($"/{font} {Fmt(size)} Tf");
        sb.AppendLine($"1 0 0 1 {Fmt(x)} {Fmt(y)} Tm");
        sb.AppendLine($"({EscapePdf(text)}) Tj");
        sb.AppendLine("ET");
    }

    private static string Fmt(decimal value) => value.ToString("0.##", CultureInfo.InvariantCulture);

    private static XElement Row(int rowIndex, params XElement[] cells) => new(SpreadsheetNs + "row", new XAttribute("r", rowIndex), cells);

    private static XElement TextCell(int columnIndex, int rowIndex, string value, int styleIndex = 0) =>
        new(SpreadsheetNs + "c",
            new XAttribute("r", CellReference(columnIndex, rowIndex)),
            new XAttribute("s", styleIndex),
            new XAttribute("t", "inlineStr"),
            new XElement(SpreadsheetNs + "is", new XElement(SpreadsheetNs + "t", value ?? string.Empty)));

    private static XElement LogoCell(int columnIndex, int rowIndex, string value) => TextCell(columnIndex, rowIndex, value, 5);

    private static XElement NumberCell(int columnIndex, int rowIndex, decimal value, int styleIndex) =>
        new(SpreadsheetNs + "c",
            new XAttribute("r", CellReference(columnIndex, rowIndex)),
            new XAttribute("s", styleIndex),
            new XElement(SpreadsheetNs + "v", value.ToString(CultureInfo.InvariantCulture)));

    private static void AddEntry(ZipArchive archive, string name, string content)
    {
        var entry = archive.CreateEntry(name, CompressionLevel.Fastest);
        using var writer = new StreamWriter(entry.Open(), new UTF8Encoding(false));
        writer.Write(content);
    }

    private static string FilterSummary(ReportExecutionResponseDTO report) =>
        report.AppliedFilters.Count == 0 ? "None" : string.Join(" | ", report.AppliedFilters.Select(kv => $"{HumanizeColumnName(kv.Key)}={kv.Value}"));

    private static string GetLogoText(string institutionName)
    {
        var tokens = institutionName.Split(new[] { ' ', '-', '_' }, StringSplitOptions.RemoveEmptyEntries).Take(3).Select(token => char.ToUpperInvariant(token[0]));
        var logo = string.Concat(tokens);
        return string.IsNullOrWhiteSpace(logo) ? "BI" : logo;
    }

    private static string HumanizeColumnName(string value)
    {
        if (string.IsNullOrWhiteSpace(value))
        {
            return string.Empty;
        }

        var normalized = new StringBuilder();
        normalized.Append(char.ToUpperInvariant(value[0]));
        for (var index = 1; index < value.Length; index++)
        {
            var current = value[index];
            var previous = value[index - 1];
            if ((char.IsUpper(current) && char.IsLower(previous)) || current is '_' or '-')
            {
                normalized.Append(' ');
            }

            normalized.Append(current is '_' or '-' ? ' ' : current);
        }

        return normalized.ToString();
    }

    private static bool TryGetDateSerial(object? value, out decimal serial)
    {
        serial = 0m;
        switch (value)
        {
            case DateTime dateTime:
                serial = Convert.ToDecimal(dateTime.ToOADate(), CultureInfo.InvariantCulture);
                return true;
            case DateOnly dateOnly:
                serial = Convert.ToDecimal(dateOnly.ToDateTime(TimeOnly.MinValue).ToOADate(), CultureInfo.InvariantCulture);
                return true;
            default:
                return false;
        }
    }

    private static bool IsNumeric(object? value) => value is byte or short or int or long or float or double or decimal;

    private static string EscapeCsv(string value)
    {
        var input = value ?? string.Empty;
        if (input.Contains(',') || input.Contains('"') || input.Contains('\n'))
        {
            return '"' + input.Replace("\"", "\"\"") + '"';
        }

        return input;
    }

    private static string FormatValue(object? value) => value switch
    {
        null => string.Empty,
        DateTime dateTime => dateTime.ToString("yyyy-MM-dd HH:mm:ss", CultureInfo.InvariantCulture),
        DateOnly dateOnly => dateOnly.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture),
        decimal number => number.ToString("0.00", CultureInfo.InvariantCulture),
        double number => number.ToString("0.00", CultureInfo.InvariantCulture),
        float number => number.ToString("0.00", CultureInfo.InvariantCulture),
        _ => Convert.ToString(value, CultureInfo.InvariantCulture) ?? string.Empty
    };

    private static string EscapePdf(string value) => (value ?? string.Empty).Replace("\\", "\\\\").Replace("(", "\\(").Replace(")", "\\)");
    private static string Truncate(string value, int max) => string.IsNullOrEmpty(value) || value.Length <= max ? value : value[..Math.Max(0, max - 1)] + "...";
    private static string SanitizeFileName(string value) => string.Concat(value.Select(ch => Path.GetInvalidFileNameChars().Contains(ch) ? '_' : ch));

    private static string CellReference(int columnIndex, int rowIndex)
    {
        var dividend = columnIndex;
        var columnName = string.Empty;
        while (dividend > 0)
        {
            var modulo = (dividend - 1) % 26;
            columnName = Convert.ToChar(65 + modulo) + columnName;
            dividend = (dividend - modulo) / 26;
        }

        return columnName + rowIndex;
    }
}
