using System;
using System.Collections.Generic;
using System.Linq;
using BankInsight.API.DTOs;
using BankInsight.API.Security;

namespace BankInsight.API.Services;

public record ReportCatalogDefinition(
    string ReportCode,
    string ReportName,
    string Category,
    string SubCategory,
    string Description,
    string DataSource,
    IReadOnlyList<string> RequiredPermissions,
    IReadOnlyList<string> ExportFormats,
    IReadOnlyList<string> ApplicableInstitutionTypes,
    IReadOnlyList<ReportParameterSchemaDTO> ParameterSchema,
    IReadOnlyList<string> DefaultColumns,
    string DefaultSort,
    bool IsRegulatory,
    bool RequiresApprovalBeforeFinalExport,
    bool SupportsBranchScope,
    bool SupportsHeadOfficeScope,
    string Version,
    DateTime? EffectiveFrom = null,
    DateTime? EffectiveTo = null,
    bool IsActive = true);

public interface IReportCatalogRegistry
{
    IReadOnlyList<ReportCatalogDefinition> GetAll();
    ReportCatalogDefinition? GetByCode(string reportCode);
}

public class ReportCatalogRegistry : IReportCatalogRegistry
{
    private static readonly IReadOnlyList<ReportCatalogDefinition> Definitions = BuildDefinitions();

    public IReadOnlyList<ReportCatalogDefinition> GetAll() => Definitions;

    public ReportCatalogDefinition? GetByCode(string reportCode) =>
        Definitions.FirstOrDefault(item => string.Equals(item.ReportCode, reportCode, StringComparison.OrdinalIgnoreCase));

    private static IReadOnlyList<ReportCatalogDefinition> BuildDefinitions()
    {
        var inst = new[] { "Bank", "Savings and Loans", "Finance House", "Microfinance", "Head Office", "Branch" };
        var exportAll = new[] { "xlsx", "csv", "pdf" };
        var exportReg = new[] { "xlsx", "csv", "pdf" };
        var baseFilters = new[]
        {
            P("fromDate", "From Date", "date", false),
            P("toDate", "To Date", "date", false),
            P("branchId", "Branch", "branch", false),
            P("currency", "Currency", "text", false, "GHS"),
        };
        var creditFilters = new[]
        {
            P("fromDate", "From Date", "date", false),
            P("toDate", "To Date", "date", false),
            P("branchId", "Branch", "branch", false),
            P("productCode", "Product", "text", false),
            P("officerId", "Officer", "text", false),
            P("providerName", "Bureau Provider", "text", false),
            P("decision", "Decision", "select", false, null, null, new[] { "PASS", "REVIEW", "FAIL", "FALLBACK" }),
            P("riskBand", "Risk Band", "select", false, null, null, new[] { "LOW", "MEDIUM", "HIGH", "UNKNOWN" }),
            P("submissionStatus", "Submission Status", "text", false),
            P("dataQualityStatus", "Data Quality", "text", false),
        };

        return new List<ReportCatalogDefinition>
        {
            Def("REG-BOG-CAPITAL-ADEQUACY", "Capital Adequacy Return", "Regulatory Reports", "Prudential / Supervisory", "Capital adequacy, tier ratios, and risk weighted assets.", "REG_CAPITAL_ADEQUACY", new[]{AppPermissions.Reports.Regulatory, AppPermissions.Reports.Generate}, exportReg, inst, baseFilters, new[]{"asOfDate","tier1Capital","tier2Capital","capitalAdequacyRatio"}, "asOfDate:desc", true, true, true, true),
            Def("REG-BOG-LIQUIDITY", "Liquidity Coverage Report", "Regulatory Reports", "Prudential / Supervisory", "Liquidity positions, reserve posture, and operational liquidity summary.", "REG_LIQUIDITY", new[]{AppPermissions.Reports.Regulatory, AppPermissions.Reports.Generate}, exportReg, inst, baseFilters, new[]{"asOfDate","currency","closingBalance","totalDeposits","totalWithdrawals"}, "asOfDate:desc", true, true, true, true),
            Def("REG-BOG-ASSET-QUALITY", "Asset Quality Report", "Regulatory Reports", "Prudential / Supervisory", "Loan quality, classifications, and NPL posture.", "REG_ASSET_QUALITY", new[]{AppPermissions.Reports.Regulatory, AppPermissions.Reports.Generate}, exportReg, inst, baseFilters, new[]{"branchId","status","parBucket","outstandingBalance"}, "outstandingBalance:desc", true, true, true, true),
            Def("REG-BOG-PROVISIONING", "Provisioning and Impairment Report", "Regulatory Reports", "Prudential / Supervisory", "Provisioning, impairment staging, and write-off support.", "REG_PROVISIONING", new[]{AppPermissions.Reports.Regulatory, AppPermissions.Reports.Generate}, exportReg, inst, baseFilters, new[]{"loanId","stage","allowanceAmount","writtenOffAt"}, "allowanceAmount:desc", true, true, true, true),
            Def("REG-BOG-LARGE-EXPOSURES", "Large Exposure Report", "Regulatory Reports", "Prudential / Supervisory", "Concentration and top obligor monitoring.", "REG_LARGE_EXPOSURE", new[]{AppPermissions.Reports.Regulatory, AppPermissions.Reports.Generate}, exportReg, inst, baseFilters, new[]{"customerId","customerName","totalExposure","percentageOfCapital"}, "totalExposure:desc", true, true, true, true),
            Def("REG-BOG-CONCENTRATION", "Sector and Branch Concentration Report", "Regulatory Reports", "Credit Risk and Portfolio Quality", "Sector, branch, and product concentration view for supervisory oversight.", "REG_CONCENTRATION", new[]{AppPermissions.Reports.Regulatory, AppPermissions.Reports.Generate}, exportReg, inst, baseFilters, new[]{"dimension","bucket","exposureAmount","loanCount"}, "exposureAmount:desc", true, true, true, true),
            Def("REG-BOG-ARREARS-AGING", "Regulatory Arrears Aging", "Regulatory Reports", "Credit Risk and Portfolio Quality", "Arrears aging with buckets, balances, and borrower distribution.", "REG_ARREARS_AGING", new[]{AppPermissions.Reports.Regulatory, AppPermissions.Reports.Generate}, exportReg, inst, baseFilters, new[]{"parBucket","loanCount","outstandingBalance"}, "outstandingBalance:desc", true, true, true, true),
            Def("REG-BOG-FEES-CHARGES", "Fees and Charges by Product", "Regulatory Reports", "Conduct / Service", "Fees and charges support report by product and transaction volume.", "REG_FEES_CHARGES", new[]{AppPermissions.Reports.Regulatory, AppPermissions.Reports.Generate}, exportReg, inst, baseFilters, new[]{"productCode","feeAmount","transactionCount"}, "feeAmount:desc", true, false, true, true),
            Def("REG-BOG-INCIDENTS", "Exception and Incident Report", "Regulatory Reports", "Conduct / Service", "Operational incidents and exceptions relevant for regulatory support review.", "REG_INCIDENTS", new[]{AppPermissions.Reports.Regulatory, AppPermissions.Reports.Generate}, exportReg, inst, baseFilters, new[]{"incidentType","branchId","amount","status"}, "reportedAt:desc", true, false, true, true),

            Def("REG-BOG-NPL-SUMMARY", "Non-Performing Loan Summary", "Regulatory Reports", "Credit Risk and Portfolio Quality", "NPL balances, borrower counts, and regulatory classification posture.", "REG_NPL_SUMMARY", new[]{AppPermissions.Reports.Regulatory, AppPermissions.Reports.Generate}, exportReg, inst, baseFilters, new[]{"parBucket","loanCount","nplBalance","nplRatio"}, "nplBalance:desc", true, true, true, true),
            Def("REG-BOG-RESTRUCTURED-LOANS", "Restructured Loan Register", "Regulatory Reports", "Credit Risk and Portfolio Quality", "Restructured, rescheduled, and watch-list facilities for regulatory review.", "REG_RESTRUCTURED_LOANS", new[]{AppPermissions.Reports.Regulatory, AppPermissions.Reports.Generate}, exportReg, inst, baseFilters, new[]{"loanId","customerName","status","outstandingBalance"}, "outstandingBalance:desc", true, true, true, true),
            Def("REG-BOG-WRITEOFF-RECOVERIES", "Write-Off and Recovery Regulatory Support", "Regulatory Reports", "Credit Risk and Portfolio Quality", "Written-off exposures, recoveries, and impairment support for returns.", "REG_WRITEOFF_RECOVERIES", new[]{AppPermissions.Reports.Regulatory, AppPermissions.Reports.Generate}, exportReg, inst, baseFilters, new[]{"loanId","isWrittenOff","recoveryAmount","allowanceAmount"}, "allowanceAmount:desc", true, true, true, true),
            Def("REG-BOG-TOP-OBLIGORS", "Top Obligors", "Regulatory Reports", "Credit Risk and Portfolio Quality", "Top borrower exposure view for supervisory monitoring.", "REG_TOP_OBLIGORS", new[]{AppPermissions.Reports.Regulatory, AppPermissions.Reports.Generate}, exportReg, inst, baseFilters, new[]{"customerId","customerName","totalExposure","loanCount"}, "totalExposure:desc", true, true, true, true),
            Def("REG-BOG-BRANCH-REG-SUMMARY", "Branch Regulatory Summary", "Regulatory Reports", "Prudential / Supervisory", "Branch-level lending, deposits, PAR, and liquidity support metrics.", "REG_BRANCH_REG_SUMMARY", new[]{AppPermissions.Reports.Regulatory, AppPermissions.Reports.Generate}, exportReg, inst, baseFilters, new[]{"branchId","loanExposure","depositBalance","parExposure"}, "loanExposure:desc", true, true, true, true),
            Def("OPS-NEW-CUSTOMERS", "New Customers", "Operational Reports", "Customer Operations", "New customers by period, branch, and segment.", "OPS_NEW_CUSTOMERS", new[]{AppPermissions.Reports.View, AppPermissions.Reports.Generate}, exportAll, inst, baseFilters, new[]{"id","name","type","createdAt","branchId"}, "createdAt:desc", false, false, true, true),
            Def("OPS-DORMANT-CUSTOMERS", "Dormant Customers", "Operational Reports", "Customer Operations", "Customers without recent transaction activity.", "OPS_DORMANT_CUSTOMERS", new[]{AppPermissions.Reports.View, AppPermissions.Reports.Generate}, exportAll, inst, baseFilters, new[]{"customerId","customerName","lastTransactionDate","accountCount"}, "daysDormant:desc", false, false, true, true),
            Def("OPS-KYC-INCOMPLETE", "KYC Incomplete Customers", "Operational Reports", "Customer Operations", "Customers with incomplete KYC posture or low KYC tier.", "OPS_KYC_INCOMPLETE", new[]{AppPermissions.Reports.View, AppPermissions.Reports.Generate}, exportAll, inst, baseFilters, new[]{"customerId","customerName","kycLevel","riskRating"}, "kycLevel:asc", false, false, true, true),
            Def("OPS-DEPOSIT-TRANSACTIONS", "Daily Deposit Transactions", "Operational Reports", "Deposit Operations", "Deposit transactions by branch, teller, and amount.", "OPS_DEPOSIT_TRANSACTIONS", new[]{AppPermissions.Reports.View, AppPermissions.Reports.Generate}, exportAll, inst, baseFilters, new[]{"transactionId","date","accountId","amount","branchId"}, "date:desc", false, false, true, true),
            Def("OPS-DEPOSIT-BALANCES", "Deposit Balances by Product", "Operational Reports", "Deposit Operations", "Account balances and volume by product type.", "OPS_DEPOSIT_BALANCES", new[]{AppPermissions.Reports.View, AppPermissions.Reports.Generate}, exportAll, inst, baseFilters, new[]{"product","accountCount","balance"}, "balance:desc", false, false, true, true),
            Def("OPS-BRANCH-DEPOSIT-PERF", "Branch Deposit Performance", "Operational Reports", "Deposit Operations", "Deposit growth and transaction contribution by branch.", "OPS_BRANCH_DEPOSIT_PERF", new[]{AppPermissions.Reports.View, AppPermissions.Reports.Generate}, exportAll, inst, baseFilters, new[]{"branchId","transactionCount","depositVolume","currentBalance"}, "depositVolume:desc", false, false, true, true),
            Def("OPS-LOAN-DISBURSEMENTS", "Loan Disbursement Report", "Operational Reports", "Loan Operations", "Disbursements by product, branch, and officer.", "OPS_LOAN_DISBURSEMENTS", new[]{AppPermissions.Reports.View, AppPermissions.Reports.Generate}, exportAll, inst, baseFilters.Concat(new[]{P("productCode","Product","text",false), P("officerId","Officer","text",false)}).ToArray(), new[]{"loanId","customerName","principal","disbursementDate","branchId"}, "disbursementDate:desc", false, false, true, true),
            Def("OPS-LOAN-REPAYMENTS", "Loan Repayment Report", "Operational Reports", "Loan Operations", "Repayment collections with branch and source analysis.", "OPS_LOAN_REPAYMENTS", new[]{AppPermissions.Reports.View, AppPermissions.Reports.Generate}, exportAll, inst, baseFilters, new[]{"loanId","repaymentDate","amount","processedBy"}, "repaymentDate:desc", false, false, true, true),
            Def("OPS-DUE-INSTALLMENTS", "Due Installments", "Operational Reports", "Loan Operations", "Installments due within the selected date range.", "OPS_DUE_INSTALLMENTS", new[]{AppPermissions.Reports.View, AppPermissions.Reports.Generate}, exportAll, inst, baseFilters, new[]{"loanId","dueDate","principal","interest","status"}, "dueDate:asc", false, false, true, true),
            Def("OPS-PAR", "Portfolio at Risk", "Operational Reports", "Loan Operations", "Portfolio at risk and bucket distribution.", "OPS_PAR", new[]{AppPermissions.Reports.View, AppPermissions.Reports.Generate}, exportAll, inst, baseFilters, new[]{"parBucket","loanCount","outstandingBalance"}, "outstandingBalance:desc", false, false, true, true),
            Def("OPS-DELINQUENT-LOANS", "Delinquent Loans", "Operational Reports", "Loan Operations", "Delinquent and matured loans with arrears monitoring.", "OPS_DELINQUENT_LOANS", new[]{AppPermissions.Reports.View, AppPermissions.Reports.Generate}, exportAll, inst, baseFilters, new[]{"loanId","customerName","parBucket","outstandingBalance"}, "outstandingBalance:desc", false, false, true, true),
            Def("OPS-GROUP-LENDING", "Group Lending Performance", "Operational Reports", "Loan Operations", "Group lending portfolio, PAR, and meeting collection view.", "OPS_GROUP_LENDING", new[]{AppPermissions.GroupLending.ViewReports, AppPermissions.Reports.Generate}, exportAll, inst, baseFilters, new[]{"groupName","members","portfolioOutstanding","parExposure"}, "portfolioOutstanding:desc", false, false, true, true),
            Def("OPS-BRANCH-TRANSACTIONS", "Branch Transaction Summary", "Operational Reports", "Branch and Teller Operations", "Transaction summaries and volumes by branch.", "OPS_BRANCH_TRANSACTIONS", new[]{AppPermissions.Reports.View, AppPermissions.Reports.Generate}, exportAll, inst, baseFilters, new[]{"branchId","transactionCount","totalAmount"}, "totalAmount:desc", false, false, true, true),
            Def("OPS-TELLER-SUMMARY", "Teller Transaction Summary", "Operational Reports", "Branch and Teller Operations", "Teller activity, cash movement, and balancing indicators.", "OPS_TELLER_SUMMARY", new[]{AppPermissions.Reports.View, AppPermissions.Reports.Generate}, exportAll, inst, baseFilters, new[]{"processedBy","transactionCount","totalAmount"}, "totalAmount:desc", false, false, true, true),
            Def("OPS-VAULT-CASH", "Vault Cash Position", "Operational Reports", "Branch and Teller Operations", "Vault cash, till cash, and GL reconciliation support.", "OPS_VAULT_CASH", new[]{AppPermissions.Reports.View, AppPermissions.Reports.Generate}, exportAll, inst, baseFilters, new[]{"branchId","vaultCash","tillCash","reconciliationVariance"}, "vaultCash:desc", false, false, true, true),
            Def("OPS-CASH-INCIDENTS", "Shortages and Excesses", "Operational Reports", "Branch and Teller Operations", "Cash shortages, excesses, and control incidents.", "OPS_CASH_INCIDENTS", new[]{AppPermissions.Reports.View, AppPermissions.Reports.Generate}, exportAll, inst, baseFilters, new[]{"incidentType","branchId","amount","status"}, "reportedAt:desc", false, false, true, true),
            Def("OPS-PENDING-APPROVALS", "Pending Approvals", "Operational Reports", "Audit and Control Operations", "Maker-checker queues and pending approvals.", "OPS_PENDING_APPROVALS", new[]{AppPermissions.Reports.View, AppPermissions.Reports.Generate}, exportAll, inst, baseFilters, new[]{"referenceType","status","requestedBy","createdAt"}, "createdAt:desc", false, false, true, true),
            Def("OPS-REVERSED-TXNS", "Reversed Transactions", "Operational Reports", "Audit and Control Operations", "Reversed and corrected transactions for control review.", "OPS_REVERSED_TRANSACTIONS", new[]{AppPermissions.Reports.View, AppPermissions.Reports.Generate}, exportAll, inst, baseFilters, new[]{"transactionId","date","amount","status"}, "date:desc", false, false, true, true),
            Def("OPS-USER-ACTIVITY", "User Activity Log", "Operational Reports", "Audit and Control Operations", "User activity and security-sensitive events.", "OPS_USER_ACTIVITY", new[]{AppPermissions.Audit.View, AppPermissions.Reports.Generate}, exportAll, inst, baseFilters, new[]{"userId","action","status","createdAt"}, "createdAt:desc", false, false, true, true),
            Def("OPS-INACTIVE-USERS", "Inactive Users", "Operational Reports", "Audit and Control Operations", "Users with no recent sessions or activity.", "OPS_INACTIVE_USERS", new[]{AppPermissions.Audit.View, AppPermissions.Reports.Generate}, exportAll, inst, baseFilters, new[]{"staffId","name","email","daysSinceLastSession"}, "daysSinceLastSession:desc", false, false, true, true),

            Def("OPS-CUSTOMER-GROWTH-TREND", "Customer Growth Trends", "Operational Reports", "Customer Operations", "Monthly customer onboarding and growth trend by branch.", "OPS_CUSTOMER_GROWTH_TREND", new[]{AppPermissions.Reports.View, AppPermissions.Reports.Generate}, exportAll, inst, baseFilters, new[]{"periodLabel","newCustomers","consumerCustomers","businessCustomers"}, "periodLabel:asc", false, false, true, true),
            Def("OPS-CUSTOMER-SEGMENTATION", "Customer Segmentation", "Operational Reports", "Customer Operations", "Consumer versus business mix with KYC and risk segmentation.", "OPS_CUSTOMER_SEGMENTATION", new[]{AppPermissions.Reports.View, AppPermissions.Reports.Generate}, exportAll, inst, baseFilters, new[]{"segment","customerCount","averageKycTier","highRiskCount"}, "customerCount:desc", false, false, true, true),
            Def("OPS-ACCOUNT-OPENING-TRENDS", "Account Opening Trends", "Operational Reports", "Customer Operations", "New account openings and balances by month and branch.", "OPS_ACCOUNT_OPENING_TRENDS", new[]{AppPermissions.Reports.View, AppPermissions.Reports.Generate}, exportAll, inst, baseFilters, new[]{"periodLabel","accountsOpened","openingBalance","branchId"}, "periodLabel:asc", false, false, true, true),
            Def("OPS-CUSTOMER-STATUS", "Customer Status Report", "Operational Reports", "Customer Operations", "Customer status mix using activity, KYC, and account posture indicators.", "OPS_CUSTOMER_STATUS", new[]{AppPermissions.Reports.View, AppPermissions.Reports.Generate}, exportAll, inst, baseFilters, new[]{"status","customerCount","accountCount"}, "customerCount:desc", false, false, true, true),
            Def("OPS-DEPOSIT-INFLOW-OUTFLOW", "Deposit Inflow and Outflow Summary", "Operational Reports", "Deposit Operations", "Deposit inflows, outflows, and net movement by branch.", "OPS_DEPOSIT_INFLOW_OUTFLOW", new[]{AppPermissions.Reports.View, AppPermissions.Reports.Generate}, exportAll, inst, baseFilters, new[]{"branchId","inflow","outflow","netFlow"}, "netFlow:desc", false, false, true, true),
            Def("OPS-OFFICER-COLLECTIONS", "Officer Collections", "Operational Reports", "Loan Operations", "Repayment collections summarized by officer or processor.", "OPS_OFFICER_COLLECTIONS", new[]{AppPermissions.Reports.View, AppPermissions.Reports.Generate}, exportAll, inst, baseFilters, new[]{"officerId","repaymentCount","collectionAmount"}, "collectionAmount:desc", false, false, true, true),
            Def("OPS-MATURED-LOANS", "Matured Loans", "Operational Reports", "Loan Operations", "Loans that have reached maturity and remain outstanding.", "OPS_MATURED_LOANS", new[]{AppPermissions.Reports.View, AppPermissions.Reports.Generate}, exportAll, inst, baseFilters, new[]{"loanId","customerName","maturityDate","outstandingBalance"}, "maturityDate:asc", false, false, true, true),
            Def("OPS-WRITTENOFF-LOANS", "Written-Off Loans", "Operational Reports", "Loan Operations", "Written-off facilities with recovery posture and allowances.", "OPS_WRITTENOFF_LOANS", new[]{AppPermissions.Reports.View, AppPermissions.Reports.Generate}, exportAll, inst, baseFilters, new[]{"loanId","customerName","writtenOffAt","allowanceAmount"}, "writtenOffAt:desc", false, false, true, true),
            Def("OPS-RECOVERIES", "Recovery Report", "Operational Reports", "Loan Operations", "Recovered amounts on impaired or written-off facilities.", "OPS_RECOVERIES", new[]{AppPermissions.Reports.View, AppPermissions.Reports.Generate}, exportAll, inst, baseFilters, new[]{"loanId","customerName","recoveryAmount","createdAt"}, "recoveryAmount:desc", false, false, true, true),
            Def("OPS-BRANCH-LOAN-PERF", "Branch Loan Performance", "Operational Reports", "Loan Operations", "Loan balances, PAR, and disbursement posture by branch.", "OPS_BRANCH_LOAN_PERF", new[]{AppPermissions.Reports.View, AppPermissions.Reports.Generate}, exportAll, inst, baseFilters, new[]{"branchId","loanCount","loanExposure","parExposure"}, "loanExposure:desc", false, false, true, true),
            Def("OPS-PRODUCT-LOAN-PERF", "Product Loan Performance", "Operational Reports", "Loan Operations", "Loan balances, PAR, and yield proxy by product.", "OPS_PRODUCT_LOAN_PERF", new[]{AppPermissions.Reports.View, AppPermissions.Reports.Generate}, exportAll, inst, baseFilters, new[]{"productCode","loanCount","loanExposure","parExposure"}, "loanExposure:desc", false, false, true, true),
            Def("OPS-FAILED-POSTINGS", "Failed Postings", "Operational Reports", "Audit and Control Operations", "Transactions and journal activity that indicate failed or exception posting outcomes.", "OPS_FAILED_POSTINGS", new[]{AppPermissions.Reports.View, AppPermissions.Reports.Generate}, exportAll, inst, baseFilters, new[]{"reference","date","amount","status"}, "date:desc", false, false, true, true),
            Def("CRB-CONSUMER-INQUIRY-LOG", "Consumer Bureau Inquiry Log", "Credit Bureau Reports", "Consumer Loans", "Consumer loan bureau checks and outcomes.", "CRB_CONSUMER_INQUIRY_LOG", new[]{AppPermissions.Reports.Risk, AppPermissions.Reports.Generate}, exportAll, inst, creditFilters, new[]{"checkedAt","customerId","providerName","score","decision"}, "checkedAt:desc", false, false, true, true),
            Def("CRB-BUSINESS-INQUIRY-LOG", "Business Bureau Inquiry Log", "Credit Bureau Reports", "Business Loans", "Business loan bureau checks and outcomes.", "CRB_BUSINESS_INQUIRY_LOG", new[]{AppPermissions.Reports.Risk, AppPermissions.Reports.Generate}, exportAll, inst, creditFilters, new[]{"checkedAt","customerId","providerName","score","decision"}, "checkedAt:desc", false, false, true, true),
            Def("CRB-CONSUMER-MISSING-CHECKS", "Consumer Loans Missing Bureau Check", "Credit Bureau Reports", "Consumer Loans", "Consumer loans lacking required bureau checks.", "CRB_CONSUMER_MISSING_CHECKS", new[]{AppPermissions.Reports.Risk, AppPermissions.Reports.Generate}, exportAll, inst, creditFilters, new[]{"loanId","customerId","productCode","status"}, "applicationDate:desc", false, false, true, true),
            Def("CRB-BUSINESS-MISSING-CHECKS", "Business Loans Missing Bureau Check", "Credit Bureau Reports", "Business Loans", "Business loans lacking required bureau checks.", "CRB_BUSINESS_MISSING_CHECKS", new[]{AppPermissions.Reports.Risk, AppPermissions.Reports.Generate}, exportAll, inst, creditFilters, new[]{"loanId","customerId","productCode","status"}, "applicationDate:desc", false, false, true, true),
            Def("CRB-PROVIDER-PERFORMANCE", "Bureau Provider Performance", "Credit Bureau Reports", "Monitoring", "Provider success, fallback, timeout, and recommendation trends.", "CRB_PROVIDER_PERFORMANCE", new[]{AppPermissions.Reports.Risk, AppPermissions.Reports.Generate}, exportAll, inst, creditFilters, new[]{"providerName","totalChecks","failedChecks","avgScore"}, "failedChecks:desc", false, false, true, true),
            Def("CRB-APPROVAL-BY-GRADE", "Approval Outcomes by Bureau Grade", "Credit Bureau Reports", "Monitoring", "Decision outcomes compared with bureau scores and grades.", "CRB_APPROVAL_BY_GRADE", new[]{AppPermissions.Reports.Risk, AppPermissions.Reports.Generate}, exportAll, inst, creditFilters, new[]{"riskGrade","bureauDecision","internalStatus","count"}, "count:desc", false, false, true, true),
            Def("CRB-FAILED-INTEGRATION", "Failed Bureau Integration Report", "Credit Bureau Reports", "Monitoring", "Timeouts, fallbacks, and failures by provider and date.", "CRB_FAILED_INTEGRATION", new[]{AppPermissions.Reports.Risk, AppPermissions.Reports.Generate}, exportAll, inst, creditFilters, new[]{"checkedAt","providerName","status","retryCount"}, "checkedAt:desc", false, false, true, true),
            Def("CRB-DATA-QUALITY", "CRB Data Quality Dashboard", "Credit Bureau Reports", "Data Quality", "Mandatory field completeness and submission-readiness dashboard.", "CRB_DATA_QUALITY", new[]{AppPermissions.Reports.Risk, AppPermissions.Reports.Generate}, exportAll, inst, creditFilters, new[]{"segment","totalRecords","missingMandatoryFields","readyRecords"}, "missingMandatoryFields:desc", false, false, true, true),
            Def("CRB-REJECTIONS", "CRB Rejected Record Report", "Credit Bureau Reports", "Data Quality", "Rejected-record tracking using regulatory return validation state.", "CRB_REJECTIONS", new[]{AppPermissions.Reports.Risk, AppPermissions.Reports.Generate}, exportAll, inst, creditFilters, new[]{"returnType","returnDate","submissionStatus","validationErrors"}, "returnDate:desc", false, false, true, true),
            Def("CRB-RESUBMISSIONS", "CRB Resubmission Report", "Credit Bureau Reports", "Data Quality", "Items returned for correction and resubmission follow-up.", "CRB_RESUBMISSIONS", new[]{AppPermissions.Reports.Risk, AppPermissions.Reports.Generate}, exportAll, inst, creditFilters, new[]{"returnType","returnDate","submissionStatus","validationErrors"}, "returnDate:desc", false, false, true, true),
            Def("CRB-CONSUMER-CREDIT-EXTRACT", "BoG Consumer Credit Extract", "Credit Bureau Reports", "BoG Extracts", "BoG-aligned consumer credit outbound extract.", "CRB_CONSUMER_CREDIT_EXTRACT", new[]{AppPermissions.Reports.Regulatory, AppPermissions.Reports.Generate}, exportReg, inst, creditFilters, new[]{"correctionIndicator","creditFacilityAccountNumber","customerId","assetClassification"}, "creditFacilityAccountNumber:asc", true, true, true, true),
            Def("CRB-BUSINESS-CREDIT-EXTRACT", "BoG Business Credit Extract", "Credit Bureau Reports", "BoG Extracts", "BoG-aligned business credit outbound extract.", "CRB_BUSINESS_CREDIT_EXTRACT", new[]{AppPermissions.Reports.Regulatory, AppPermissions.Reports.Generate}, exportReg, inst, creditFilters, new[]{"correctionIndicator","creditFacilityAccountNumber","customerId","assetClassification"}, "creditFacilityAccountNumber:asc", true, true, true, true),
            Def("CRB-CONSUMER-DISHONOURED-EXTRACT", "BoG Consumer Dishonoured Cheque Extract", "Credit Bureau Reports", "BoG Extracts", "BoG-aligned consumer dishonoured cheque extract.", "CRB_CONSUMER_DISHONOURED_EXTRACT", new[]{AppPermissions.Reports.Regulatory, AppPermissions.Reports.Generate}, exportReg, inst, creditFilters, new[]{"customerId","accountId","amount","date"}, "date:desc", true, true, true, true),
            Def("CRB-BUSINESS-DISHONOURED-EXTRACT", "BoG Business Dishonoured Cheque Extract", "Credit Bureau Reports", "BoG Extracts", "BoG-aligned business dishonoured cheque extract.", "CRB_BUSINESS_DISHONOURED_EXTRACT", new[]{AppPermissions.Reports.Regulatory, AppPermissions.Reports.Generate}, exportReg, inst, creditFilters, new[]{"customerId","accountId","amount","date"}, "date:desc", true, true, true, true),
            Def("CRB-CONSUMER-JUDGMENT-EXTRACT", "BoG Consumer Judgment Extract", "Credit Bureau Reports", "BoG Extracts", "BoG-aligned consumer judgment extract.", "CRB_CONSUMER_JUDGMENT_EXTRACT", new[]{AppPermissions.Reports.Regulatory, AppPermissions.Reports.Generate}, exportReg, inst, creditFilters, new[]{"customerId","loanId","status","outstandingBalance"}, "outstandingBalance:desc", true, true, true, true),
            Def("CRB-BUSINESS-JUDGMENT-EXTRACT", "BoG Business Judgment Extract", "Credit Bureau Reports", "BoG Extracts", "BoG-aligned business judgment extract.", "CRB_BUSINESS_JUDGMENT_EXTRACT", new[]{AppPermissions.Reports.Regulatory, AppPermissions.Reports.Generate}, exportReg, inst, creditFilters, new[]{"customerId","loanId","status","outstandingBalance"}, "outstandingBalance:desc", true, true, true, true),

            Def("CRB-CONSUMER-APPLICATION-SCORES", "Consumer Applications with Bureau Scores", "Credit Bureau Reports", "Consumer Loans", "Consumer loan applications with bureau outcomes, scores, and internal decision posture.", "CRB_CONSUMER_APPLICATION_SCORES", new[]{AppPermissions.Reports.Risk, AppPermissions.Reports.Generate}, exportAll, inst, creditFilters, new[]{"applicationDate","loanId","customerName","score","internalStatus"}, "applicationDate:desc", false, false, true, true),
            Def("CRB-BUSINESS-APPLICATION-SCORES", "Business Applications with Bureau Scores", "Credit Bureau Reports", "Business Loans", "Business loan applications with bureau outcomes, scores, and internal decision posture.", "CRB_BUSINESS_APPLICATION_SCORES", new[]{AppPermissions.Reports.Risk, AppPermissions.Reports.Generate}, exportAll, inst, creditFilters, new[]{"applicationDate","loanId","customerName","score","internalStatus"}, "applicationDate:desc", false, false, true, true),
            Def("CRB-CONSUMER-DECLINED-BY-BUREAU", "Consumer Declined Loans Due to Bureau Result", "Credit Bureau Reports", "Consumer Loans", "Consumer applications declined or held back because of adverse bureau outcomes.", "CRB_CONSUMER_DECLINED_BY_BUREAU", new[]{AppPermissions.Reports.Risk, AppPermissions.Reports.Generate}, exportAll, inst, creditFilters, new[]{"loanId","customerName","decision","score","internalStatus"}, "applicationDate:desc", false, false, true, true),
            Def("CRB-BUSINESS-DECLINED-BY-BUREAU", "Business Declined Loans Due to Bureau Result", "Credit Bureau Reports", "Business Loans", "Business applications declined or held back because of adverse bureau outcomes.", "CRB_BUSINESS_DECLINED_BY_BUREAU", new[]{AppPermissions.Reports.Risk, AppPermissions.Reports.Generate}, exportAll, inst, creditFilters, new[]{"loanId","customerName","decision","score","internalStatus"}, "applicationDate:desc", false, false, true, true),
            Def("CRB-CONSUMER-EXPOSURE-COMPARISON", "Consumer External vs Internal Exposure", "Credit Bureau Reports", "Consumer Loans", "Consumer external bureau exposure compared with internal balances.", "CRB_CONSUMER_EXPOSURE_COMPARISON", new[]{AppPermissions.Reports.Risk, AppPermissions.Reports.Generate}, exportAll, inst, creditFilters, new[]{"customerId","customerName","internalExposure","externalExposure","variance"}, "variance:desc", false, false, true, true),
            Def("CRB-BUSINESS-EXPOSURE-COMPARISON", "Business External vs Internal Exposure", "Credit Bureau Reports", "Business Loans", "Business external bureau exposure compared with internal balances.", "CRB_BUSINESS_EXPOSURE_COMPARISON", new[]{AppPermissions.Reports.Risk, AppPermissions.Reports.Generate}, exportAll, inst, creditFilters, new[]{"customerId","customerName","internalExposure","externalExposure","variance"}, "variance:desc", false, false, true, true),
            Def("CRB-CONSUMER-DEFAULT-SUMMARY", "Consumer Default Marker Summary", "Credit Bureau Reports", "Consumer Loans", "Consumer delinquency and default indicators grouped by bureau risk band.", "CRB_CONSUMER_DEFAULT_SUMMARY", new[]{AppPermissions.Reports.Risk, AppPermissions.Reports.Generate}, exportAll, inst, creditFilters, new[]{"riskBand","defaultedLoans","currentLoans","totalExposure"}, "defaultedLoans:desc", false, false, true, true),
            Def("CRB-BUSINESS-DEFAULT-SUMMARY", "Business Default Marker Summary", "Credit Bureau Reports", "Business Loans", "Business delinquency and default indicators grouped by bureau risk band.", "CRB_BUSINESS_DEFAULT_SUMMARY", new[]{AppPermissions.Reports.Risk, AppPermissions.Reports.Generate}, exportAll, inst, creditFilters, new[]{"riskBand","defaultedLoans","currentLoans","totalExposure"}, "defaultedLoans:desc", false, false, true, true),
            Def("CRB-CONSUMER-OVERDUE-LAST-CHECK", "Consumer Overdue Loans with Last Bureau Check", "Credit Bureau Reports", "Consumer Loans", "Overdue consumer loans alongside the most recent bureau inquiry date.", "CRB_CONSUMER_OVERDUE_LAST_CHECK", new[]{AppPermissions.Reports.Risk, AppPermissions.Reports.Generate}, exportAll, inst, creditFilters, new[]{"loanId","customerName","parBucket","lastCheckDate","outstandingBalance"}, "lastCheckDate:desc", false, false, true, true),
            Def("CRB-BUSINESS-OVERDUE-LAST-CHECK", "Business Overdue Loans with Last Bureau Check", "Credit Bureau Reports", "Business Loans", "Overdue business loans alongside the most recent bureau inquiry date.", "CRB_BUSINESS_OVERDUE_LAST_CHECK", new[]{AppPermissions.Reports.Risk, AppPermissions.Reports.Generate}, exportAll, inst, creditFilters, new[]{"loanId","customerName","parBucket","lastCheckDate","outstandingBalance"}, "lastCheckDate:desc", false, false, true, true),
            Def("CRB-CONSUMER-SUBMISSION-READINESS", "Consumer CRB Submission Readiness", "Credit Bureau Reports", "Data Quality", "Consumer extract readiness, mandatory field completeness, and validation posture.", "CRB_CONSUMER_SUBMISSION_READINESS", new[]{AppPermissions.Reports.Risk, AppPermissions.Reports.Generate}, exportAll, inst, creditFilters, new[]{"creditFacilityAccountNumber","customerId","readinessStatus","missingFields"}, "readinessStatus:asc", false, false, true, true),
            Def("CRB-BUSINESS-SUBMISSION-READINESS", "Business CRB Submission Readiness", "Credit Bureau Reports", "Data Quality", "Business extract readiness, mandatory field completeness, and validation posture.", "CRB_BUSINESS_SUBMISSION_READINESS", new[]{AppPermissions.Reports.Risk, AppPermissions.Reports.Generate}, exportAll, inst, creditFilters, new[]{"creditFacilityAccountNumber","customerId","readinessStatus","missingFields"}, "readinessStatus:asc", false, false, true, true),
            Def("CRB-CONSUMER-DISHONOURED-REPORT", "Consumer Dishonoured Cheque Report", "Credit Bureau Reports", "Dishonoured Cheque", "Consumer dishonoured cheque reporting dataset and monitoring view.", "CRB_CONSUMER_DISHONOURED_REPORT", new[]{AppPermissions.Reports.Risk, AppPermissions.Reports.Generate}, exportAll, inst, creditFilters, new[]{"customerId","accountId","amount","date"}, "date:desc", false, false, true, true),
            Def("CRB-BUSINESS-DISHONOURED-REPORT", "Business Dishonoured Cheque Report", "Credit Bureau Reports", "Dishonoured Cheque", "Business dishonoured cheque reporting dataset and monitoring view.", "CRB_BUSINESS_DISHONOURED_REPORT", new[]{AppPermissions.Reports.Risk, AppPermissions.Reports.Generate}, exportAll, inst, creditFilters, new[]{"customerId","accountId","amount","date"}, "date:desc", false, false, true, true),
            Def("CRB-CONSUMER-JUDGMENT-REPORT", "Consumer Judgment Report", "Credit Bureau Reports", "Judgment", "Consumer judgment-oriented reporting dataset and monitoring view.", "CRB_CONSUMER_JUDGMENT_REPORT", new[]{AppPermissions.Reports.Risk, AppPermissions.Reports.Generate}, exportAll, inst, creditFilters, new[]{"customerId","loanId","status","outstandingBalance"}, "outstandingBalance:desc", false, false, true, true),
            Def("CRB-BUSINESS-JUDGMENT-REPORT", "Business Judgment Report", "Credit Bureau Reports", "Judgment", "Business judgment-oriented reporting dataset and monitoring view.", "CRB_BUSINESS_JUDGMENT_REPORT", new[]{AppPermissions.Reports.Risk, AppPermissions.Reports.Generate}, exportAll, inst, creditFilters, new[]{"customerId","loanId","status","outstandingBalance"}, "outstandingBalance:desc", false, false, true, true),
            Def("CRB-PENDING-DATA-COMPLETION", "Pending Cheque and Judgment Data Completion", "Credit Bureau Reports", "Data Quality", "Cheque or judgment records that still need mandatory data completion before submission.", "CRB_PENDING_DATA_COMPLETION", new[]{AppPermissions.Reports.Risk, AppPermissions.Reports.Generate}, exportAll, inst, creditFilters, new[]{"recordType","customerId","recordReference","missingFields"}, "recordType:asc", false, false, true, true),
            Def("CRB-MISSING-MANDATORY-FIELDS", "Missing Mandatory Field Report", "Credit Bureau Reports", "Data Quality", "Mandatory-field validation gaps across CRB-oriented datasets.", "CRB_MISSING_MANDATORY_FIELDS", new[]{AppPermissions.Reports.Risk, AppPermissions.Reports.Generate}, exportAll, inst, creditFilters, new[]{"recordType","customerId","recordReference","missingFields"}, "recordType:asc", false, false, true, true),
            Def("CRB-INQUIRY-VOLUME-COMPARISON", "Consumer vs Business Inquiry Volumes", "Credit Bureau Reports", "Monitoring", "Comparative bureau inquiry volume by applicant segment and month.", "CRB_INQUIRY_VOLUME_COMPARISON", new[]{AppPermissions.Reports.Risk, AppPermissions.Reports.Generate}, exportAll, inst, creditFilters, new[]{"periodLabel","consumerChecks","businessChecks","totalChecks"}, "periodLabel:asc", false, false, true, true),
            Def("CRB-BRANCH-USAGE", "Branch-wise Bureau Usage", "Credit Bureau Reports", "Monitoring", "Bureau checks summarized by branch, decisions, and failure posture.", "CRB_BRANCH_USAGE", new[]{AppPermissions.Reports.Risk, AppPermissions.Reports.Generate}, exportAll, inst, creditFilters, new[]{"branchId","totalChecks","failedChecks","averageScore"}, "totalChecks:desc", false, false, true, true),
            Def("CRB-OFFICER-USAGE", "Officer-wise Bureau Usage", "Credit Bureau Reports", "Monitoring", "Bureau checks summarized by originating officer or maker.", "CRB_OFFICER_USAGE", new[]{AppPermissions.Reports.Risk, AppPermissions.Reports.Generate}, exportAll, inst, creditFilters, new[]{"officerId","totalChecks","failedChecks","averageScore"}, "totalChecks:desc", false, false, true, true),
            Def("CRB-PRODUCT-DEPENDENCY", "Product-wise Bureau Dependency", "Credit Bureau Reports", "Monitoring", "Product-level bureau usage, decision outcomes, and failure rates.", "CRB_PRODUCT_DEPENDENCY", new[]{AppPermissions.Reports.Risk, AppPermissions.Reports.Generate}, exportAll, inst, creditFilters, new[]{"productCode","totalChecks","failedChecks","averageScore"}, "totalChecks:desc", false, false, true, true),
            Def("CRB-AVERAGE-SCORE-BY-SEGMENT", "Average Score by Loan Segment", "Credit Bureau Reports", "Monitoring", "Average bureau score by customer segment and risk band.", "CRB_AVERAGE_SCORE_BY_SEGMENT", new[]{AppPermissions.Reports.Risk, AppPermissions.Reports.Generate}, exportAll, inst, creditFilters, new[]{"segment","riskBand","averageScore","checkCount"}, "averageScore:desc", false, false, true, true),
            Def("CRB-PENDING-RESPONSES", "Pending Applications Awaiting Bureau Response", "Credit Bureau Reports", "Monitoring", "Pending bureau checks and applications awaiting final provider responses.", "CRB_PENDING_RESPONSES", new[]{AppPermissions.Reports.Risk, AppPermissions.Reports.Generate}, exportAll, inst, creditFilters, new[]{"checkedAt","customerId","providerName","status"}, "checkedAt:desc", false, false, true, true),
            Def("CRB-BUREAU-OVERRIDE", "Bureau Override Report", "Credit Bureau Reports", "Monitoring", "Cases where internal approval overrode an adverse bureau recommendation.", "CRB_BUREAU_OVERRIDE", new[]{AppPermissions.Reports.Risk, AppPermissions.Reports.Generate}, exportAll, inst, creditFilters, new[]{"loanId","customerName","bureauDecision","internalStatus"}, "checkedAt:desc", false, false, true, true),
            Def("CRB-REJECTION-TREND", "CRB Rejection Trend", "Credit Bureau Reports", "Monitoring", "Trend of rejected CRB submissions by month and return type.", "CRB_REJECTION_TREND", new[]{AppPermissions.Reports.Risk, AppPermissions.Reports.Generate}, exportAll, inst, creditFilters, new[]{"periodLabel","returnType","rejectedCount"}, "periodLabel:asc", false, false, true, true),
            Def("FIN-TRIAL-BALANCE-DETAIL", "Trial Balance Detailed", "Accounting & Finance Reports", "Trial Balance", "Detailed trial balance by GL account.", "FIN_TRIAL_BALANCE_DETAIL", new[]{AppPermissions.Reports.Financial, AppPermissions.Reports.Generate}, exportAll, inst, baseFilters, new[]{"accountNumber","accountName","debitBalance","creditBalance"}, "accountNumber:asc", false, false, true, true),
            Def("FIN-TRIAL-BALANCE-SUMMARY", "Trial Balance Summary", "Accounting & Finance Reports", "Trial Balance", "Summary trial balance with total debits and credits.", "FIN_TRIAL_BALANCE_SUMMARY", new[]{AppPermissions.Reports.Financial, AppPermissions.Reports.Generate}, exportAll, inst, baseFilters, new[]{"accountClass","debitBalance","creditBalance"}, "accountClass:asc", false, false, true, true),
            Def("FIN-GL-TRANSACTIONS", "GL Transactions", "Accounting & Finance Reports", "General Ledger", "Journal lines and GL movement detail.", "FIN_GL_TRANSACTIONS", new[]{AppPermissions.Reports.Financial, AppPermissions.Reports.Generate}, exportAll, inst, baseFilters, new[]{"journalId","date","accountCode","debit","credit"}, "date:desc", false, false, true, true),
            Def("FIN-JOURNAL-LISTING", "Journal Listing", "Accounting & Finance Reports", "General Ledger", "Journal entry listing and source summary.", "FIN_JOURNAL_LISTING", new[]{AppPermissions.Reports.Financial, AppPermissions.Reports.Generate}, exportAll, inst, baseFilters, new[]{"journalId","date","reference","status"}, "date:desc", false, false, true, true),
            Def("FIN-BALANCE-SHEET", "Balance Sheet", "Accounting & Finance Reports", "Financial Statements", "Statement of financial position.", "FIN_BALANCE_SHEET", new[]{AppPermissions.Reports.Financial, AppPermissions.Reports.Generate}, exportAll, inst, baseFilters, new[]{"section","lineItem","amount"}, "section:asc", false, false, true, true),
            Def("FIN-INCOME-STATEMENT", "Income Statement", "Accounting & Finance Reports", "Financial Statements", "Profit and loss statement.", "FIN_INCOME_STATEMENT", new[]{AppPermissions.Reports.Financial, AppPermissions.Reports.Generate}, exportAll, inst, baseFilters, new[]{"section","lineItem","amount"}, "section:asc", false, false, true, true),
            Def("FIN-CASH-FLOW", "Cash Flow Statement", "Accounting & Finance Reports", "Financial Statements", "Cash flow statement by operating, investing, and financing activities.", "FIN_CASH_FLOW", new[]{AppPermissions.Reports.Financial, AppPermissions.Reports.Generate}, exportAll, inst, baseFilters, new[]{"category","activity","amount"}, "category:asc", false, false, true, true),
            Def("FIN-LOANS-ADVANCES", "Loans and Advances Schedule", "Accounting & Finance Reports", "Supporting Schedules", "Loans and advances support schedule.", "FIN_LOANS_ADVANCES", new[]{AppPermissions.Reports.Financial, AppPermissions.Reports.Generate}, exportAll, inst, baseFilters, new[]{"loanId","customerName","principal","outstandingBalance"}, "outstandingBalance:desc", false, false, true, true),
            Def("FIN-CUSTOMER-DEPOSITS", "Customer Deposits Schedule", "Accounting & Finance Reports", "Supporting Schedules", "Customer deposit schedule by account type and branch.", "FIN_CUSTOMER_DEPOSITS", new[]{AppPermissions.Reports.Financial, AppPermissions.Reports.Generate}, exportAll, inst, baseFilters, new[]{"accountId","customerName","balance","type"}, "balance:desc", false, false, true, true),
            Def("FIN-IMPAIRMENT-SUPPORT", "Impairment and ECL Support", "Accounting & Finance Reports", "IFRS Supporting Reports", "Impairment staging and loan loss support.", "FIN_IMPAIRMENT_SUPPORT", new[]{AppPermissions.Reports.Financial, AppPermissions.Reports.Generate}, exportAll, inst, baseFilters, new[]{"loanId","stage","allowanceAmount","isWrittenOff"}, "allowanceAmount:desc", false, false, true, true),
            Def("FIN-WRITEOFF-MOVEMENT", "Write-Off and Recovery Movement", "Accounting & Finance Reports", "IFRS Supporting Reports", "Write-off and recovery movement schedule.", "FIN_WRITEOFF_MOVEMENT", new[]{AppPermissions.Reports.Financial, AppPermissions.Reports.Generate}, exportAll, inst, baseFilters, new[]{"loanId","isWrittenOff","recoveryAmount","createdAt"}, "createdAt:desc", false, false, true, true),

            Def("FIN-LEDGER-STATEMENT", "Ledger Statement", "Accounting & Finance Reports", "General Ledger", "Ledger statement by account with movement totals and balances.", "FIN_LEDGER_STATEMENT", new[]{AppPermissions.Reports.Financial, AppPermissions.Reports.Generate}, exportAll, inst, baseFilters, new[]{"accountCode","accountName","totalDebit","totalCredit","netMovement"}, "accountCode:asc", false, false, true, true),
            Def("FIN-ACCOUNT-ACTIVITY", "Account Activity", "Accounting & Finance Reports", "General Ledger", "Account activity summary using customer account transactions.", "FIN_ACCOUNT_ACTIVITY", new[]{AppPermissions.Reports.Financial, AppPermissions.Reports.Generate}, exportAll, inst, baseFilters, new[]{"accountId","customerName","transactionCount","netMovement"}, "netMovement:desc", false, false, true, true),
            Def("FIN-JOURNAL-SOURCE-SUMMARY", "Journal Source Summary", "Accounting & Finance Reports", "General Ledger", "Journal counts and values by source or posting status.", "FIN_JOURNAL_SOURCE_SUMMARY", new[]{AppPermissions.Reports.Financial, AppPermissions.Reports.Generate}, exportAll, inst, baseFilters, new[]{"source","journalCount","postedCount"}, "journalCount:desc", false, false, true, true),
            Def("FIN-STATEMENT-CHANGES-EQUITY", "Statement of Changes in Equity", "Accounting & Finance Reports", "Financial Statements", "Equity opening, movement, and closing support statement.", "FIN_STATEMENT_CHANGES_EQUITY", new[]{AppPermissions.Reports.Financial, AppPermissions.Reports.Generate}, exportAll, inst, baseFilters, new[]{"lineItem","openingBalance","movement","closingBalance"}, "lineItem:asc", false, false, true, true),
            Def("FIN-CASH-EQUIVALENTS", "Cash and Cash Equivalents", "Accounting & Finance Reports", "Supporting Schedules", "Cash, bank, vault, and near-cash balance support schedule.", "FIN_CASH_EQUIVALENTS", new[]{AppPermissions.Reports.Financial, AppPermissions.Reports.Generate}, exportAll, inst, baseFilters, new[]{"source","currency","amount"}, "amount:desc", false, false, true, true),
            Def("FIN-BANK-BALANCES", "Bank Balances", "Accounting & Finance Reports", "Supporting Schedules", "Bank and current account balances for treasury and finance support.", "FIN_BANK_BALANCES", new[]{AppPermissions.Reports.Financial, AppPermissions.Reports.Generate}, exportAll, inst, baseFilters, new[]{"accountId","customerName","balance","currency"}, "balance:desc", false, false, true, true),
            Def("FIN-ACCRUED-INCOME", "Accrued Income", "Accounting & Finance Reports", "Supporting Schedules", "Interest accrued but not yet realized on the loan portfolio.", "FIN_ACCRUED_INCOME", new[]{AppPermissions.Reports.Financial, AppPermissions.Reports.Generate}, exportAll, inst, baseFilters, new[]{"loanId","accrualDate","interestAccrued","isPosted"}, "accrualDate:desc", false, false, true, true),
            Def("FIN-ACCRUED-EXPENSES", "Accrued Expenses", "Accounting & Finance Reports", "Supporting Schedules", "Expense and liability balances flagged as accrued or payable.", "FIN_ACCRUED_EXPENSES", new[]{AppPermissions.Reports.Financial, AppPermissions.Reports.Generate}, exportAll, inst, baseFilters, new[]{"accountCode","lineItem","amount"}, "amount:desc", false, false, true, true),
            Def("FIN-SUSPENSE-BALANCES", "Suspense Balances", "Accounting & Finance Reports", "Supporting Schedules", "Suspense and unresolved balances requiring reconciliation.", "FIN_SUSPENSE_BALANCES", new[]{AppPermissions.Reports.Financial, AppPermissions.Reports.Generate}, exportAll, inst, baseFilters, new[]{"accountCode","lineItem","amount"}, "amount:desc", false, false, true, true),
            Def("FIN-SUSPENDED-VS-ACCRUED-INTEREST", "Suspended vs Accrued Interest", "Accounting & Finance Reports", "IFRS Supporting Reports", "Comparison of suspended-interest loans against accrued interest balances.", "FIN_SUSPENDED_VS_ACCRUED_INTEREST", new[]{AppPermissions.Reports.Financial, AppPermissions.Reports.Generate}, exportAll, inst, baseFilters, new[]{"loanId","isSuspendedInterest","accruedInterest","status"}, "accruedInterest:desc", false, false, true, true),
            Def("MGT-BRANCH-PROFITABILITY", "Branch Profitability", "Management Reports", "Performance", "Branch performance and contribution view based on transaction and loan income proxies.", "MGT_BRANCH_PROFITABILITY", new[]{AppPermissions.Reports.View, AppPermissions.Reports.Generate}, exportAll, inst, baseFilters, new[]{"branchId","depositBalance","loanBalance","estimatedIncome"}, "estimatedIncome:desc", false, false, true, true),
            Def("MGT-PRODUCT-PROFITABILITY", "Product Profitability", "Management Reports", "Performance", "Product performance by balances and yield proxy.", "MGT_PRODUCT_PROFITABILITY", new[]{AppPermissions.Reports.View, AppPermissions.Reports.Generate}, exportAll, inst, baseFilters, new[]{"productCode","loanBalance","estimatedIncome"}, "estimatedIncome:desc", false, false, true, true),
            Def("MGT-PERFORMANCE-TREND", "MTD/QTD/YTD Performance", "Management Reports", "Performance", "Period performance comparison view.", "MGT_PERFORMANCE_TREND", new[]{AppPermissions.Reports.View, AppPermissions.Reports.Generate}, exportAll, inst, baseFilters, new[]{"periodLabel","depositVolume","loanDisbursement","netFlow"}, "periodLabel:asc", false, false, true, true),
            Def("AUDIT-CONTROL-EXCEPTIONS", "Audit and Control Exceptions", "Audit & Control Reports", "Control", "Combined exceptions across audit, approvals, reversals, and failed activities.", "AUDIT_CONTROL_EXCEPTIONS", new[]{AppPermissions.Audit.View, AppPermissions.Reports.Generate}, exportAll, inst, baseFilters, new[]{"source","status","description","createdAt"}, "createdAt:desc", false, false, true, true),
        };
    }

    private static ReportCatalogDefinition Def(
        string code,
        string name,
        string category,
        string subCategory,
        string description,
        string dataSource,
        IReadOnlyList<string> permissions,
        IReadOnlyList<string> exportFormats,
        IReadOnlyList<string> institutionTypes,
        IReadOnlyList<ReportParameterSchemaDTO> parameters,
        IReadOnlyList<string> defaultColumns,
        string defaultSort,
        bool isRegulatory,
        bool requiresApproval,
        bool branchScope,
        bool headOfficeScope) =>
        new(code, name, category, subCategory, description, dataSource, permissions, exportFormats, institutionTypes, parameters, defaultColumns, defaultSort, isRegulatory, requiresApproval, branchScope, headOfficeScope, "1.0", DateTime.UtcNow.Date);

    private static ReportParameterSchemaDTO P(string name, string label, string type, bool required, string? defaultValue = null, string? placeholder = null, IEnumerable<string>? options = null) =>
        new()
        {
            Name = name,
            Label = label,
            Type = type,
            Required = required,
            DefaultValue = defaultValue,
            Placeholder = placeholder,
            Options = options?.ToList() ?? new List<string>()
        };
}

