namespace HybridTransfer.Application.DTOs;

public sealed record RegisterRequest(string Email, string PhoneNumber, string FullName, string AcceptedTermsVersion, string IdempotencyKey);
public sealed record AuthResponse(Guid CustomerId, string AccessToken, string RefreshToken, DateTimeOffset ExpiresAtUtc);
public sealed record WalletSummaryResponse(Guid WalletId, string Currency, decimal AvailableBalance, decimal ReservedBalance, string Status);
public sealed record ConversionQuoteRequest(string FromCurrency, string ToCurrency, decimal Amount);
public sealed record ConversionQuoteResponse(Guid QuoteId, decimal Rate, decimal Spread, decimal Fee, DateTimeOffset ExpiresAtUtc);
public sealed record InternalTransferRequest(Guid SourceWalletId, string DestinationCustomerNumber, decimal Amount, string Currency, string? Narrative);
public sealed record LedgerInternalTransferRequest(Guid SourceWalletId, Guid DestinationWalletId, Guid SourceLiabilityAccountId, Guid DestinationLiabilityAccountId, decimal Amount, string Currency, string Reference);
public sealed record LedgerSettlementRequest(Guid TransferOrderId, Guid PendingPayoutLiabilityAccountId, Guid SettlementAssetAccountId, decimal Amount, string Currency, string Reference);
public sealed record LedgerReversalRequest(Guid TransferOrderId, Guid CustomerWalletId, Guid PendingPayoutLiabilityAccountId, Guid CustomerLiabilityAccountId, decimal Amount, string Currency, string Reference, Guid ReversedJournalEntryId);
public sealed record LedgerPostingResponse(Guid JournalEntryId, string Status, Guid SourceWalletId, Guid DestinationWalletId, decimal Amount, string Currency);
public sealed record LedgerSimplePostingResponse(Guid JournalEntryId, string Status, decimal Amount, string Currency, string Reference, Guid? TransferOrderId);
public sealed record JournalLineResponse(Guid LedgerAccountId, decimal Debit, decimal Credit, string Currency, string Narrative);
public sealed record JournalEntryDetailResponse(Guid JournalEntryId, string Reference, string Status, string SourceModule, string IdempotencyKey, Guid? TransferOrderId, Guid? ReversalOfJournalEntryId, IReadOnlyCollection<JournalLineResponse> Lines);
public sealed record TransferDetailResponse(Guid TransferOrderId, string Type, string Channel, string Status, string RiskStatus, string ComplianceStatus, string? PartnerReference, string? FailureReason, decimal Amount, decimal Fee, Guid SourceWalletId);
public sealed record AuditEventResponse(Guid AuditEventId, string Action, string EntityType, string EntityId, string ActorId, DateTimeOffset CreatedAtUtc, string? BeforeJson, string? AfterJson);
public sealed record TransferExplorerQueryRequest(string? Status, string? Channel, string? Reference, DateTimeOffset? CreatedFromUtc, DateTimeOffset? CreatedToUtc, int Page = 1, int PageSize = 25);
public sealed record JournalExplorerQueryRequest(string? Status, string? SourceModule, string? Reference, Guid? TransferOrderId, DateTimeOffset? BookingFromUtc, DateTimeOffset? BookingToUtc, int Page = 1, int PageSize = 25);
public sealed record AuditExplorerQueryRequest(string? EntityType, string? EntityId, string? Action, DateTimeOffset? CreatedFromUtc, DateTimeOffset? CreatedToUtc, int Page = 1, int PageSize = 25);
public sealed record ApprovalExplorerQueryRequest(string? Status, string? ActionCode, Guid? TransferOrderId, string? RequestedBy, DateTimeOffset? CreatedFromUtc, DateTimeOffset? CreatedToUtc, int Page = 1, int PageSize = 25);
public sealed record AlertExplorerQueryRequest(string? Status, string? Severity, Guid? CustomerId, string? AlertCode, DateTimeOffset? CreatedFromUtc, DateTimeOffset? CreatedToUtc, int Page = 1, int PageSize = 25);
public sealed record PagedResponse<T>(int Page, int PageSize, int TotalCount, IReadOnlyCollection<T> Items);
public sealed record TransferExplorerItemResponse(Guid TransferOrderId, string Type, string Channel, string Status, string RiskStatus, string ComplianceStatus, string? PartnerReference, decimal Amount, string CreatedBy, DateTimeOffset CreatedAtUtc);
public sealed record JournalEntryExplorerItemResponse(Guid JournalEntryId, string Reference, string Status, string SourceModule, Guid? TransferOrderId, Guid? ReversalOfJournalEntryId, decimal TotalDebit, decimal TotalCredit, int LineCount, DateTimeOffset BookingDateUtc);
public sealed record AuditEventExplorerItemResponse(Guid AuditEventId, string Action, string EntityType, string EntityId, string ActorId, string ActorType, DateTimeOffset CreatedAtUtc);
public sealed record ApprovalExplorerItemResponse(Guid ApprovalRequestId, Guid TransferOrderId, string ActionCode, string Status, string RequestedBy, string? ApprovedBy, string Reason, DateTimeOffset CreatedAtUtc);
public sealed record AlertExplorerItemResponse(Guid AlertId, Guid CustomerId, string AlertCode, string Severity, int Score, string Status, DateTimeOffset CreatedAtUtc, string Summary);
public sealed record MobileMoneyTransferRequest(Guid SourceWalletId, string MomoNumber, string Network, decimal Amount, string Currency, string BeneficiaryName, string? Narrative);
public sealed record CryptoWithdrawalRequest(Guid SourceWalletId, string Asset, string Network, string DestinationAddress, decimal Amount, string? TravelRuleReference);
public sealed record TransferResponse(Guid TransferId, string Status, string RiskStatus, string ComplianceStatus, string? ProviderReference);
public sealed record DepositAddressRequest(Guid WalletId, string Asset, string Network);
public sealed record DepositAddressResponse(string WalletAddress, string Asset, string Network, int RequiredConfirmations);
public sealed record WebhookEnvelope(string ProviderCode, string EventType, string ExternalReference, string Payload, string? SignatureHeader);
public sealed record AlertResponse(Guid AlertId, Guid CustomerId, string AlertCode, string Severity, int Score, string Status, string Summary);
public sealed record ApprovalQueueItemResponse(Guid ApprovalRequestId, Guid TransferOrderId, string ActionCode, string Status, string RequestedBy, string Reason, DateTimeOffset CreatedAtUtc);
public sealed record ReconciliationItemResponse(Guid ReconciliationItemId, string ReconciliationType, string ExternalReference, string InternalReference, decimal Amount, string Currency, string Status, string Notes);
public sealed record ApprovalDecisionRequest(string ApprovedBy, string Decision, string DecisionNotes);
public sealed record ManualReconciliationRequest(string ReconciliationType, string ExternalReference, string InternalReference, decimal Amount, string Currency, string Notes);
public sealed record CustomerSummaryResponse(Guid CustomerId, string CustomerNumber, string FullName, string KycTier, string KycStatus, string RiskRating, string Status);
public sealed record KycSubmissionResponse(Guid CustomerId, string KycStatus, string KycTier, bool RequiresEnhancedDueDiligence);
public sealed record ReportDescriptorResponse(string ReportCode, string Name, string Description, string Format, string GenerationMode);
