using MudBlazor;

namespace CoreBanker.Navigation;

public sealed record AppRouteDefinition(
    string Route,
    string Title,
    string Subtitle,
    string Group,
    string Icon,
    IReadOnlyList<string> Permissions,
    bool ShowInShortcuts = false);

public static class AppRouteRegistry
{
    public static readonly IReadOnlyList<AppRouteDefinition> Routes =
    [
        new("/dashboard", "Operational Overview", "Track portfolio movement, transaction activity, and audit posture from one workspace.", "Dashboard", Icons.Material.Filled.Dashboard, ["dashboard.view"], true),
        new("/clients", "Client List", "Search and review customer records, status, and onboarding readiness.", "Clients", Icons.Material.Filled.People, ["customers.view"], true),
        new("/clients/onboard", "Client Onboarding", "Register new clients and capture the initial operating profile.", "Clients", Icons.Material.Filled.PersonAdd, ["customers.create"]),
        new("/accounts", "Accounts", "Open deposit accounts and review account balances and product usage.", "Accounts", Icons.Material.Filled.AccountBalance, ["accounts.view", "VIEW_ACCOUNTS"], true),
        new("/microfinance-operations", "Microfinance Operations", "Manage collector assignments, susu collections, compulsory savings, and field batch settlement.", "Microfinance", Icons.Material.Filled.Storefront, ["transactions.post", "transactions.create", "POST_TRANSACTIONS"], true),
        new("/teller", "Teller Operations", "Post live counter transactions through the active teller station.", "Teller", Icons.Material.Filled.PointOfSale, ["transactions.post", "transactions.create", "POST_TRANSACTIONS"], true),
        new("/transactions", "Transaction Explorer", "Review posted and pending transactions across the branch network.", "Transactions", Icons.Material.Filled.ReceiptLong, ["transactions.view", "VIEW_TRANSACTIONS"], true),
        new("/digital-banking", "Digital Banking", "Manage digital savings, investments, lending, and eligibility from a unified workspace.", "Digital Banking", Icons.Material.Filled.PhoneIphone, ["accounts.view", "VIEW_ACCOUNTS"], true),
        new("/customer-360", "Customer 360", "Review relationship health, exposures, and customer activity in one place.", "Clients", Icons.Material.Filled.AccountCircle, ["customers.view"], true),
        new("/relationship-banking", "Relationship Banking", "Track customer value, engagement, and priority relationship signals.", "Clients", Icons.Material.Filled.Handshake, ["customers.view"], true),
        new("/loans", "Loan Management", "Monitor origination, portfolio status, and repayment performance.", "Loan Management", Icons.Material.Filled.Money, ["loans.view", "VIEW_LOANS"], true),
        new("/collections-recoveries", "Collections & Recoveries", "Track delinquent facilities, promises to pay, and recovery actions.", "Loan Management", Icons.Material.Filled.AssignmentLate, ["loans.view", "VIEW_LOANS"], true),
        new("/collateral-covenants", "Collateral & Covenants", "Govern security perfection, valuation expiry, and covenant compliance.", "Loan Management", Icons.Material.Filled.Gavel, ["loans.view", "VIEW_LOANS"], true),
        new("/approvals", "Approval Inbox", "Review requests waiting on maker-checker approval and operational sign-off.", "Approvals", Icons.Material.Filled.Verified, ["approvals.view", "VIEW_APPROVALS", "workflow.view"], true),
        new("/accounting", "Accounting", "Manage GL accounts and journal activity for the banking ledger.", "Accounting", Icons.Material.Filled.Calculate, ["gl.view", "VIEW_GL", "MANAGE_GL"]),
        new("/reporting", "Reporting", "Preview reports and operational outputs generated by the platform.", "Reporting", Icons.Material.Filled.Assessment, ["reports.view", "VIEW_REPORTS"]),
        new("/treasury", "Treasury", "Track cash positions, investments, and treasury controls.", "Treasury", Icons.Material.Filled.Savings, ["gl.view", "VIEW_GL", "reports.risk"]),
        new("/fintech-platform", "Fintech Platform", "Launch the hybrid transfer workspace for custodial wallets, payouts, compliance, and reconciliation.", "Platform", Icons.Material.Filled.AccountBalanceWallet, ["dashboard.view", "accounts.view", "VIEW_ACCOUNTS"], true),
        new("/vault", "Vault Operations", "Monitor vault balances, till support, and cash control operations.", "Vault", Icons.Material.Filled.Lock, ["transactions.post", "POST_TRANSACTIONS", "gl.view"]),
        new("/operations-risk", "Operations & Risk", "Review penalties, NPL exposure, and operating risk indicators.", "Operations & Risk", Icons.Material.Filled.Warning, ["audit.view", "reports.risk", "gl.view"]),
        new("/operations-control", "Operations Control", "Supervise enterprise queues, controls, and exception handling.", "Operations & Risk", Icons.Material.Filled.DashboardCustomize, ["accounts.view", "VIEW_ACCOUNTS"], true),
        new("/digital-channel-ops", "Digital Channel Ops", "Monitor channel usage, complaints, KYC refresh workload, and session risk.", "Operations & Risk", Icons.Material.Filled.Devices, ["audit.view"], true),
        new("/reconciliation-settlement", "Reconciliation & Settlement", "Work unresolved treasury, cash, and branch settlement breaks.", "Operations & Risk", Icons.Material.Filled.FactCheck, ["gl.view", "VIEW_GL"], true),
        new("/audit", "Audit Trail", "Inspect audit events, exceptions, and operator actions.", "Audit", Icons.Material.Filled.Search, ["audit.view"]),
        new("/security-ops", "Security Operations", "Review sessions, devices, alerts, and suspicious activity.", "Security Ops", Icons.Material.Filled.Security, ["audit.view", "users.manage", "MANAGE_USERS"]),
        new("/migration", "Migration Workbench", "Import legacy datasets through governed migration batches.", "Migration", Icons.Material.Filled.UploadFile, ["users.manage", "MANAGE_USERS"]),
        new("/bankingos", "BankingOS Control", "Manage process packs, forms, themes, and runtime BankingOS assets.", "BankingOS", Icons.Material.Filled.SettingsApplications, ["processes.view", "tasks.view", "processes.manage", "VIEW_WORKFLOWS", "MANAGE_WORKFLOWS"]),
        new("/products", "Products", "Review and configure product definitions and parameters.", "Products", Icons.Material.Filled.Category, ["loans.products.configure", "group-lending.products.configure", "VIEW_PRODUCTS", "MANAGE_PRODUCTS"]),
        new("/product-factory", "Product Factory", "Control governed product lifecycle stages and run launch simulations.", "Products", Icons.Material.Filled.Science, ["loans.products.configure", "group-lending.products.configure", "VIEW_PRODUCTS", "MANAGE_PRODUCTS"], true),
        new("/settings", "Settings", "Manage system configuration, menus, and application controls.", "Settings", Icons.Material.Filled.Settings, ["VIEW_CONFIG", "MANAGE_CONFIG", "roles.manage", "MANAGE_ROLES", "users.manage", "MANAGE_USERS", "branches.manage", "VIEW_ROLES"]),
        new("/developer-portal", "Developer Portal", "Govern API products, partner applications, and webhook subscriptions.", "Settings", Icons.Material.Filled.Api, ["VIEW_CONFIG", "MANAGE_CONFIG", "roles.manage", "MANAGE_ROLES", "users.manage", "MANAGE_USERS"]),
        new("/regulatory-intelligence", "Regulatory Intelligence", "Review ORASS readiness, queue health, and submission variances.", "Settings", Icons.Material.Filled.Policy, ["reports.regulatory"], true),
        new("/extensibility", "Extensibility", "Validate dynamic forms and extension points exposed by the platform.", "Extensibility", Icons.Material.Filled.Extension, ["processes.view", "tasks.view", "processes.manage", "VIEW_WORKFLOWS", "MANAGE_WORKFLOWS"]),
        new("/workspaces", "Workspace Views", "Switch between role-based views and operating perspectives.", "Workspaces", Icons.Material.Filled.DashboardCustomize, ["dashboard.view", "audit.view", "reports.view"]),
        new("/statements", "Statements", "Verify statement outputs and customer-facing account documents.", "Statements", Icons.Material.Filled.Description, ["reports.financial", "reports.view", "VIEW_REPORTS"]),
        new("/eod", "End Of Day", "Monitor operational close activities and end-of-day readiness.", "End of Day", Icons.Material.Filled.Event, ["gl.post", "POST_JOURNAL", "gl.view", "VIEW_GL", "MANAGE_GL"]),
        new("/group-lending", "Group Lending", "Supervise lending groups, meetings, and group portfolio activity.", "Group Lending", Icons.Material.Filled.Groups, ["group-lending.view", "group-lending.reports.view", "VIEW_GROUPS"])
    ];

    public static IEnumerable<IGrouping<string, AppRouteDefinition>> GetMenuSections(IEnumerable<string> permissions)
    {
        var permissionSet = permissions.ToHashSet(StringComparer.OrdinalIgnoreCase);
        return Routes
            .Where(route => route.Permissions.Any(permissionSet.Contains))
            .GroupBy(route => route.Group);
    }

    public static IReadOnlyList<AppRouteDefinition> GetAccessibleRoutes(IEnumerable<string> permissions)
    {
        var permissionSet = permissions.ToHashSet(StringComparer.OrdinalIgnoreCase);
        return Routes
            .Where(route => route.Permissions.Any(permissionSet.Contains))
            .ToList();
    }

    public static AppRouteDefinition? GetByUri(string absoluteUri)
    {
        if (!Uri.TryCreate(absoluteUri, UriKind.Absolute, out var uri))
        {
            return null;
        }

        return Routes.FirstOrDefault(route =>
            string.Equals(route.Route, uri.AbsolutePath, StringComparison.OrdinalIgnoreCase));
    }

    public static string GetDefaultRoute(IEnumerable<string> permissions)
    {
        var permissionSet = permissions.ToHashSet(StringComparer.OrdinalIgnoreCase);
        return Routes.FirstOrDefault(route => route.ShowInShortcuts && route.Permissions.Any(permissionSet.Contains))?.Route
            ?? Routes.FirstOrDefault(route => route.Permissions.Any(permissionSet.Contains))?.Route
            ?? "/dashboard";
    }

    public static IReadOnlyList<AppRouteDefinition> GetShortcutRoutes(IEnumerable<string> permissions)
    {
        var permissionSet = permissions.ToHashSet(StringComparer.OrdinalIgnoreCase);
        return Routes
            .Where(route => route.ShowInShortcuts && route.Permissions.Any(permissionSet.Contains))
            .Take(6)
            .ToList();
    }
}
