using MudBlazor;

namespace CoreBanker.Navigation;

public sealed record AppRouteDefinition(
    string Route,
    string Title,
    string Subtitle,
    string Group,
    string Icon,
    string Permission,
    bool ShowInShortcuts = false);

public static class AppRouteRegistry
{
    public static readonly IReadOnlyList<AppRouteDefinition> Routes =
    [
        new("/dashboard", "Operational Overview", "Track portfolio movement, transaction activity, and audit posture from one workspace.", "Dashboard", Icons.Material.Filled.Dashboard, "dashboard.view", true),
        new("/clients", "Client List", "Search and review customer records, status, and onboarding readiness.", "Clients", Icons.Material.Filled.People, "customers.view", true),
        new("/clients/onboard", "Client Onboarding", "Register new clients and capture the initial operating profile.", "Clients", Icons.Material.Filled.PersonAdd, "customers.create"),
        new("/accounts", "Accounts", "Open deposit accounts and review account balances and product usage.", "Accounts", Icons.Material.Filled.AccountBalance, "accounts.view", true),
        new("/teller", "Teller Operations", "Post live counter transactions through the active teller station.", "Teller", Icons.Material.Filled.PointOfSale, "transactions.create", true),
        new("/transactions", "Transaction Explorer", "Review posted and pending transactions across the branch network.", "Transactions", Icons.Material.Filled.ReceiptLong, "transactions.view", true),
        new("/loans", "Loan Management", "Monitor origination, portfolio status, and repayment performance.", "Loan Management", Icons.Material.Filled.Money, "loans.view", true),
        new("/approvals", "Approval Inbox", "Review requests waiting on maker-checker approval and operational sign-off.", "Approvals", Icons.Material.Filled.Verified, "approvals.view", true),
        new("/accounting", "Accounting", "Manage GL accounts and journal activity for the banking ledger.", "Accounting", Icons.Material.Filled.Calculate, "gl.view"),
        new("/reporting", "Reporting", "Preview reports and operational outputs generated by the platform.", "Reporting", Icons.Material.Filled.Assessment, "reports.view"),
        new("/treasury", "Treasury", "Track cash positions, investments, and treasury controls.", "Treasury", Icons.Material.Filled.Savings, "treasury.view"),
        new("/vault", "Vault Operations", "Monitor vault balances, till support, and cash control operations.", "Vault", Icons.Material.Filled.Lock, "vault.view"),
        new("/operations-risk", "Operations & Risk", "Review penalties, NPL exposure, and operating risk indicators.", "Operations & Risk", Icons.Material.Filled.Warning, "operations.view"),
        new("/audit", "Audit Trail", "Inspect audit events, exceptions, and operator actions.", "Audit", Icons.Material.Filled.Search, "audit.view"),
        new("/security-ops", "Security Operations", "Review sessions, devices, alerts, and suspicious activity.", "Security Ops", Icons.Material.Filled.Security, "security.view"),
        new("/migration", "Migration Workbench", "Import legacy datasets through governed migration batches.", "Migration", Icons.Material.Filled.UploadFile, "migration.view"),
        new("/bankingos", "BankingOS Control", "Manage process packs, forms, themes, and runtime BankingOS assets.", "BankingOS", Icons.Material.Filled.SettingsApplications, "bankingos.view"),
        new("/products", "Products", "Review and configure product definitions and parameters.", "Products", Icons.Material.Filled.Category, "products.view"),
        new("/settings", "Settings", "Manage system configuration, menus, and application controls.", "Settings", Icons.Material.Filled.Settings, "settings.view"),
        new("/extensibility", "Extensibility", "Validate dynamic forms and extension points exposed by the platform.", "Extensibility", Icons.Material.Filled.Extension, "extensibility.view"),
        new("/workspaces", "Workspace Views", "Switch between role-based views and operating perspectives.", "Workspaces", Icons.Material.Filled.DashboardCustomize, "workspaces.view"),
        new("/statements", "Statements", "Verify statement outputs and customer-facing account documents.", "Statements", Icons.Material.Filled.Description, "statements.view"),
        new("/eod", "End Of Day", "Monitor operational close activities and end-of-day readiness.", "End of Day", Icons.Material.Filled.Event, "eod.view"),
        new("/group-lending", "Group Lending", "Supervise lending groups, meetings, and group portfolio activity.", "Group Lending", Icons.Material.Filled.Groups, "groups.view")
    ];

    public static IEnumerable<IGrouping<string, AppRouteDefinition>> GetMenuSections(IEnumerable<string> permissions)
    {
        var permissionSet = permissions.ToHashSet(StringComparer.OrdinalIgnoreCase);
        return Routes
            .Where(route => permissionSet.Contains(route.Permission))
            .GroupBy(route => route.Group);
    }

    public static AppRouteDefinition? GetByUri(string absoluteUri)
    {
        if (!Uri.TryCreate(absoluteUri, UriKind.Absolute, out var uri))
        {
            return null;
        }

        return Routes.FirstOrDefault(route =>
            string.Equals(route.Route, uri.AbsolutePath, StringComparison.OrdinalIgnoreCase));
    }

    public static string GetDefaultRoute(IEnumerable<string> permissions)
    {
        var permissionSet = permissions.ToHashSet(StringComparer.OrdinalIgnoreCase);
        return Routes.FirstOrDefault(route => route.ShowInShortcuts && permissionSet.Contains(route.Permission))?.Route
            ?? Routes.FirstOrDefault(route => permissionSet.Contains(route.Permission))?.Route
            ?? "/dashboard";
    }

    public static IReadOnlyList<AppRouteDefinition> GetShortcutRoutes(IEnumerable<string> permissions)
    {
        var permissionSet = permissions.ToHashSet(StringComparer.OrdinalIgnoreCase);
        return Routes
            .Where(route => route.ShowInShortcuts && permissionSet.Contains(route.Permission))
            .Take(6)
            .ToList();
    }
}
